### ISSUE TITLE
Google Analytics auth flow

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#1007]
**Describe the bug**
Google Analytics authenticated in the Analytics App triggers a direct db query. Does not create an audit trail. Add values into the analytics settings - no clear view of user actions.

**Expected behavior**
GA is auth flow in the Analytics App -  needs to communicate with the instances-api to complete this action

**Screenshots**
![image](https://user-images.githubusercontent.com/50595614/159811332-a14a6189-9b5a-44bd-b17f-21dbc7f42269.png)
![image](https://user-images.githubusercontent.com/50595614/159811346-7af64673-9501-48eb-aa51-d09535259fe1.png)

**Comment by shrunyan** [comment]
This app has be extracted out into the marketplace
