### ISSUE TITLE
MUI Button integration

### ISSUE THREAD

**Issue by agalin920** [zesty-io/manager-ui#1037]
- Kind -> Variant
  - '' [default] = contained 
    - e.g. <Button kind=''> => <Button variant='contained'>
  - outlined = outlined
  - flat = text [default] 
    - e.g. <Button kind='flat'> => <Button>
  - reversed = custom sx / custom styled or deprecate* (not used)
- Type -> Color
  - ''[default] = primary [default]
    -  - e.g. <Button type=''> => <Button>
  - secondary = secondary
  - save = success
  - alt = warning
  - warn = error
  - info = info
  - cancel = outlined version of primary or secondary
- Size => Size (see if we can maintain MUI button sizes or if we need to adjust)
  - default = medium [default]
    - - e.g. <Button size=''> => <Button> 
  - small = small
  - compact = deprecate* (only used by CopyButton)
- Buttons with icons
  - Use startIcon or endIcon prop
    - e.g. <Button><FontAwesome icon={faSomething}/></Button>  => <Button startIcon={<FontAwesome icon={faSomething}/>}>Hello</Button>   
- Text -> Child Node
  - ex: <Button text='hi' /> -> <Button>hi</Button>
- fullWidth prop when button must take up full width
- Remove any conflicting stylesheet on button
- Replace any styles from stylesheet with sx prop if needed

<Box sx={{my: 2}} >
<Stack direction='row' gap={2}><button/><button/><button/></Stack>
Example of Icon only button `<Button><DeleteIcon /></Button>`

**Comment by d88naimi** [comment]
WIP Buttons 
- [ ] Dashboard:  /content - DashboardCardFooter.js 
- [ ] Instance.js:  /settings/instance/general Save button
- [ ]
