### ISSUE TITLE
Cannot add additional fields to content model

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#1077]
Customer is not able to add a field to the following model:
instance: 8-bcb5faf2c5-gn8557
model: 6-9295e2f7a0-347l6b
This is the message they are receiving
![image (14)](https://user-images.githubusercontent.com/9896546/168647695-ab024458-5ec8-4d1c-a81b-1309c4cafb97.png)

**Comment by agalin920** [comment]
500 internal server error on https://8-bcb5faf2c5-gn8557.api.dev.zesty.io/v1/content/models/6-9295e2f7a0-347l6b/fields endpoint

**Comment by rjpals** [comment]
@giseleblair is the customer still experiencing this issue?

I've tested in dev, and I recieved a few intermittent 500 errors that prevented me from reaching the page for this model, however I was eventually able to create a new field on the aforementioned model `6-9295e2f7a0-347l6b`.

![Screen Shot 2023-01-25 at 8 23 43 PM](https://user-images.githubusercontent.com/16678143/214735059-7407ba35-9fe5-48b7-8fb8-a16873f4ed65.png)

**Comment by giseleblair** [comment]
@rjpals this can be closed
