### ISSUE TITLE
Dropdown field in the schema app does not allows options to be updated

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#1085]
**Describe the bug**
Bug affecting dropdown fields in Manager UI - preventing users from creating necessary fields:
The dropdown field's options can not be adjusted or updated. After deleting the preset option and creating a new option the same behavior persists

**To Reproduce**
1. Go to model
2. add a dropdown field
3. try to adjust options

**Expected behavior**
options should be adjustable by users during creation and updating

**Screenshots**
![image](https://user-images.githubusercontent.com/50595614/168697104-2b58dacd-0eac-4b90-af9a-b88901990bb2.png)

**Comment by shrunyan** [comment]
@d88naimi lets also fix the delete button

**Comment by shrunyan** [comment]
fix deployed
