### ISSUE TITLE
Update external link field to accept the standard 2000 characters for a url

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#1086]
**Is your feature request related to a problem? Please describe.**
Currently, our external link field has a character count limit of 150, however browsers allow for over 2000 characters (depending on browser), with 2000 as the standard.

With the field limit in place, users have taking to using text fields and/or textarea fields. This is not an ideal workflow.

**Describe the solution you'd like**
Character count in the database reflects the standard 2000 characters and the field is updated to reflect the same.

![image](https://user-images.githubusercontent.com/50595614/168858197-9f73e18d-38c3-48be-89e9-8641b42221a4.png)

**Comment by ardeay** [comment]
@agalin920 the input will need an option to control lenth.
