### ISSUE TITLE
Release App

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#111]
**Is your feature request related to a problem? Please describe.**
Coordinating publish is currently not possible in the UI experience. Additionally because all publishing must be done as separate actions it triggers multiple cache purges causing undue load on origin as pages are continually purged.

Initial instance launch is a confusing and error prone process. While an instance is being built often pages are not published so once a domain is added and traffic sent to the instance it can become a scramble to find and publish all necessary pages. For large (100 to 1000+) pages this can be prohibitive and a major issue.

**Describe the solution you'd like**
An application for coordinating queued publishing across content, code and settings.

## Queuing
Single item (content and code) views would need a "queue" in addition to the exiting publish action. Once queued they then could be published from the release app.

Alternative, and probably better, should the release app allow for searching to find all unpublished items? How would version rollbacks work in this experience?

## Release
Would the UI begin to make invidivual publish requests for queued items? Would there be a specialized RPC endpoint which allows submission of publish instructions for multiple resources?

### Release Versions

Would we track releases as versions? Could you see historical actions taken in a release? i.e. a "changelist"

Should we allow release "notes" so the user making a release can add additional written context to explain purpose/intention of release.?

### Release Roll Backs

 What if a release was a mistake? How would multiple items that were published be rolled back? Without a roll back feature this would be problematic to do manually across a large release.

## Purging

Once a release is completed, i.e. all records are in the state they should be, a purge requests would be needed which accounted for all affected resources, including related resources. Would "soft" purges be allowed in this workflow?

**Additional context**

Workflows to be accounted for

- instance launch needing to publish all or selective files
- code feature release needing multiple file publishes.
  - how would this work with a branch feature?
- content publishing which requires multiple items being published at the same time
- version roll backs
- would this account for scheduling?

**Comment by shrunyan** [comment]
Potentially related to https://github.com/zesty-io/manager-ui/issues/42

**Comment by kakoga** [comment]
what if the release calendar looked something like a colorful gantt chart
![release-app-wireframe](https://user-images.githubusercontent.com/16694502/111713960-d6862500-880d-11eb-8cc3-35772907ae49.png)

**Comment by shrunyan** [comment]
Closed https://github.com/zesty-io/manager-ui/pull/911
