### ISSUE TITLE
Dropdown field hidden in create item screen

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#1121]
**Is your feature request related to a problem? Please describe.**
When creating a new multi-entry or dataset content item dropdown options can become hidden under the meta portion of the item. Users are viewing this as a bug because the ability to scroll and view the rest of the dropdown selections is not obvious to the user. In the video you can see the behavior outlined.

**Video:**
[https://www.loom.com/share/2c94da5217d741ceb4532b4e9246a87b](https://www.loom.com/share/2c94da5217d741ceb4532b4e9246a87b)

**Describe the solution you'd like**
A clear user experience in the behaviors available or change the dropdown direction

**Comment by shrunyan** [comment]
Fixed https://github.com/zesty-io/manager-ui/pull/1163
