### ISSUE TITLE
Tab highlight gets lost when navigating to SEO&META/HEAD TAGS/HEADLESS sub tabs

### ISSUE THREAD

**Issue by agalin920** [zesty-io/manager-ui#1153]
While the tab highlight works when on the Edit Content sub-tab when navigating to any other subtab the highlight gets lost

**To Reproduce**
1. Go to Content Editor
2. Click on any Content Item
3. Click on SEO & META sub header
4. See tav no longer being highlighted

**Expected behavior**
Tab remains highlighted

**Screenshots**
<img width="439" alt="Screen Shot 2022-06-08 at 9 41 36 AM" src="https://user-images.githubusercontent.com/10054410/172671477-d8e2f188-8cf5-4ce7-b28a-7e376abd77f1.png">
<img width="445" alt="Screen Shot 2022-06-08 at 9 41 28 AM" src="https://user-images.githubusercontent.com/10054410/172671483-c164aced-9ba1-4337-bec3-b015eb61d721.png">

**Comment by shrunyan** [comment]
@agalin920 is this still an issue? The screenshot seems to indicate the seo&meta tab is highlighted.

**Comment by rjpals** [comment]
@shrunyan I believe he's talking about the highlight on the global tabs, not the underline on the page tabs. In which case, I suggest we label this `WONT FIX` as the new tabs experience will throw this out anyway.

**Comment by rjpals** [comment]
No longer relevant with new Tabs experience. Closed via #1301
