### ISSUE TITLE
Links to audit trial within manager are pointing to the wrong location/relative path

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#1157]
**Describe the bug**
Within the notification drawer, the `View All Logs` link routes to the wrong relative path of `/audit-trail` rather than in `/reports/audit-trial`. 

Inside the footer bucket of each code file has the same behavior of routing to the wrong relative path of `/audit-trail` rather than in `/reports/audit-trial`, when the `View All Logs` is clicked.

Displays as though audit trail is broken

**To Reproduce**
1. open instance 
2. click on `View All Logs` link in either the notification drawer or the footer 
3. directs to broken URL address due to missing `/reports/` path part

**Expected behavior**
should route to `/reports/audit-trial`

**Video**
https://www.loom.com/share/7db998ffb1c94df6ba4aad5fe449af5f

**Comment by shrunyan** [comment]
Resolved https://github.com/zesty-io/manager-ui/pull/1158/files
