### ISSUE TITLE
SEO loading layout

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#1159]
**Describe the bug**
When SEO app is loading it does not assume the view ports full height and so doses not display the loading message in the center of the screen.

**To Reproduce**
1. Go to /seo

**Expected behavior**
Loading message should be vertically and horizontally centered in the sub app view port

**Screenshots**
![image](https://user-images.githubusercontent.com/208819/172718449-7d7b5307-b153-413e-9b9b-47d0deabfe14.png)

**Comment by d88naimi** [comment]
PR: https://github.com/zesty-io/manager-ui/pull/1160
