### ISSUE TITLE
When `Show site name in meta title` setting is turned on, the google preview reflects this in the SEO & Meta tab of a content item

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#1170]
**Is your feature request related to a problem? Please describe.**
When `Show site name in meta title` setting is turned on, the google preview reflects this in the SEO & Meta tab of a content item  - By appending the Clippings Site Name to the end of the Title

**Additional context**
![image](https://user-images.githubusercontent.com/50595614/173423010-751b1256-1055-464c-94bf-f96216d293c1.png)
![image](https://user-images.githubusercontent.com/50595614/173423253-44fb0b7b-d2b7-487d-bd78-5649d382fa82.png)

**Comment by giseleblair** [comment]
@agalin920 the site_name value is now always being displayed in the preview. If a user turns the `Show site name in meta title` setting to OFF, they are still seeing it in the preview. This issue has not been resolved so I am reopening it.
