### ISSUE TITLE
Schema app field and model settings character counts

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#1218]
**Describe the bug**
In the schema app the **field label**, **field name**, and **description** all have character count functionality that in not outputting. The updating of the field does adjust the count. and on load the 0 character count is not displayed 

In the schema app the **model settings parsley reference name** character count works but is oversized for the navigation and shift the form downward

Video and images below 

**To Reproduce**
1. Go to schema app
2. Click on any field and the model settings 
3. the errors are immediately visible

**Screenshots**

**Video**
https://www.loom.com/share/0ef4a721474d44298ee7caa4b07eb88a

**Image**
![image](https://user-images.githubusercontent.com/50595614/176791420-87622949-c338-4481-ad27-961b63e34c76.png)

**Comment by shrunyan** [comment]
Not relevant with https://github.com/zesty-io/manager-ui/pull/1866
