### ISSUE TITLE
Improve access denied screen

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#124]
**Is your feature request related to a problem? Please describe.**
When someone tries to access an instance they do not have permission to while logged into a valid account session they receive the access denied screen.  While this is the desired outcome from a security/access perspective it leaves room for improvement.

**Describe the solution you'd like**
I think there are 2 primary ways we can improve this screen.

1) Provide the user with a path forward. If a user attempts to access an instance they do not have permission to this is most likely not malicious but a missing invitation. We should create a button which will trigger a message (email) to the instance owner noting the user wants access.

2) Track failed access and report to instance operators. While failed access is most likely a miscommunication on invites it could be an attempt at malicious access. In either case it will be beneficial information for the instance operator. We should be track these invites in zesty (audit trail?) and allowing away for operators to view this data (audit trail?)

- capture user zuid and time of who tried to access instance

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/208819/94589191-d1222780-0239-11eb-8b57-c5b2c5081134.png)

**Comment by shrunyan** [comment]
@d88naimi take a look at this issue. Provide any thoughts you have on how we could improve this. I think this could be a quick win.

**Comment by d88naimi** [comment]
@shrunyan 

If the user got to the 403 page by accident, having the option of a  “Previous Page” button would help take the user back to the last page they left off without having to re-navigate to where they last left off.

Including the Nav Header allows the user to navigate to another desired destination. 

“Get Access” button could fire off a modal with a brief description on  “ failed access is most likely a miscommunication on invites”. Provide a button to (email) to the instance owner noting the user wants access. The modal also would include a “Cancel” button and “Contact Support” button . 

Beside the message “ You do not have access……” I think we should add a 403 status code, maybe even an icon/image adding a little visual to the page lightening the negative message. 

Attached are a couple reference 
https://dribbble.com/shots/3269698-403-Forbidden-page
https://dribbble.com/shots/3464120-Access-Denied 
https://dribbble.com/shots/3958645-Error-403
https://dribbble.com/shots/3051862-SalesExec-Error-Page
