### ISSUE TITLE
Monaco editor did not adjust to the the new size of the browser when drag to a bigger monitor.

### ISSUE THREAD

**Issue by markelmad** [zesty-io/manager-ui#1275]
**Describe the bug**
When the page where the code editor is open resides on a smaller monitor and then dragged to a bigger monitor, the canvas of the editor retains its size instead of adjusting to the bigger size of the screen (browser)

**To Reproduce**
1. Use a browser on a smaller screen. Must be fresh (refresh the page first)
2. Drag the tab to a bigger screen into maximize screen.

**Expected behavior**
Monaco editor will retain its size canvas from previous browser size.

![Screenshot 2022-08-05 065437](https://user-images.githubusercontent.com/3361467/182968772-1d8bb0a6-c447-4b4d-9e63-b1f6231e278e.png)

**Desktop (please complete the following information):**
 - Windows 11
 - MS Edge
 - Version 103.0.1264.77 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shrunyan** [comment]
Sounds like we need an on resize window event handler to re-render monaco when the viewport changes. You may need to look into how monaco determines the element dimensions as it controls that styling.

Additionally I think this can be reproduced by simply drag and expanding the window.
