### ISSUE TITLE
Importing CSV into SEO app redirects always creates wildcard redirects

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#1305]
**Describe the bug**
when importing a CSV file into the SEO app for redirects - the UI indicates `Import CSV does not allow for external and wildcard redirects`. 
![image](https://user-images.githubusercontent.com/50595614/185963796-85b8069b-4901-44d0-983c-ccff592d7908.png)

However, once the redirects are applied they are all created as a Wildcard redirect. The importing CSV process does not accept item zuids as the `target`, which are necessary for the internal link redirect API endpoint: 
[Create Redirect Endpoint](https://instances-api.zesty.org/#38bf3fb8-44b1-4b22-a743-376c42fda624)
It only accepts a relative path on the incoming CSV

nor does it allow for the selection of `page` as the `targetType`, which is also needed for the internal link redirect creation. the UI automatically applies the `path` as the `targetType`, which is designated as the wildcard `targetType`. 

**To Reproduce**
1. Go to SEO app
2. Click on Import CSV/XML
3. upload file 
4. click add redirects to see the outcome

**Expected behavior**
creates internal redirects as indicated by the UI. Or allows the user to import a CSV that has all the specifications the API endpoint needs so the user can create a specified type of redirect or only allow for the internal link values on the CSV

**Screenshots**
Video:
https://www.loom.com/share/183da842cb284890a41a9f4c8049583e

**Comment by shrunyan** [comment]
I believe we should with the expected behavior of;
>  allows the user to import a CSV that has all the specifications the API
