### ISSUE TITLE
Schema App: Dropdown field type does not allow for spaces in value

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#1343]
When the user selects the Dropdown field type in schema and they are configuring the values for each dropdown option, the UI does not allow the user to have spaces or capital letters in the value field. 

The API does allow for capital letters and spaces and so the UI should also allow for the same formatting options. 

<img width="770" alt="Screen Shot 2022-09-08 at 2 35 56 PM" src="https://user-images.githubusercontent.com/9896546/189201133-df15594a-ab2a-4615-963f-d097f935fa77.png">

**Comment by giseleblair** [comment]
<img width="579" alt="Screen Shot 2022-09-14 at 6 22 54 PM" src="https://user-images.githubusercontent.com/9896546/190273819-a793a333-e58b-4418-8c38-d399c4958e72.png">

This is what the JSON output looks like with spaces, it does not break the output

**Comment by JacobDiazCruz** [comment]
@giseleblair Just to confirm, based on the discussion last time I just have to validate the inputted format on the Option value field and allow users to have the freedom for their desired formats right?

**Comment by giseleblair** [comment]
Yes and do not change spaces into "_" or lowercase capital letters
