### ISSUE TITLE
Feature: Welcome Landing App

### ISSUE THREAD

**Issue by ardeay** [zesty-io/manager-ui#142]
Welcome app landing should have a couple boxes with info and recently edited. A home/dashboard icon should be top nav.

Layout boxes like this

![image](https://user-images.githubusercontent.com/729972/94718016-f2e8e080-0305-11eb-80bf-18c7668709a5.png)
or with instances (hit accounts api) and recent edit (use audit trail with user zuid as filter)
![image](https://user-images.githubusercontent.com/729972/94719179-aef6db00-0307-11eb-8c86-0dd731a17eb4.png)
 
Content for the boxes below, also use the icons that are in the nav:

**Content**
Content entry and management.

**Schema**
Build and manage content models. 

**WebEngine Preview**
(use global icon)
Open a WebEngine preview for this instance**

**Web IDE**
Edit content templates, css, js, or make custom file types.

**Settings**
Configure your content instance.

**Audit Trail**
Explore activity on this instance.

** Redirects **
Control 300 redirects for WebEngine

**Comment by shrunyan** [comment]
Solved https://github.com/zesty-io/manager-ui/issues/472#
