### ISSUE TITLE
Content App: Update Device Resolutions

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1446]
These sizes are very old. 
![image](https://user-images.githubusercontent.com/22625919/197250568-c73809ba-5d98-4aa1-9b05-fb4a702f1fd1.png)

**Please update device viewport resolutions to the following list:** 
![Viewport List](https://user-images.githubusercontent.com/22625919/197286108-a488e6da-f11d-4722-8fa8-68c8fb721ed0.png)

@shrunyan need to know if we can do tablet and desktop sizes. See above example I am suggesting.

**Comment by zcolah** [comment]
Let us complete this ticket with only the mobile device sizes to get started.

**Comment by shrunyan** [comment]
The device shapes are being rendered with CSS. This is quite complicated styling not something we are looking to update. To replicate the experience with newer models we should use images of the devices we would like to display. This requires sourcing clean accurately sized images of these devices.

**Comment by shrunyan** [comment]
Additional the list of devices offered should probably be consistent with current global market share. e.g. https://www.counterpointresearch.com/top-5-smartphone-model-share-8-countries/

**Comment by zcolah** [comment]
@shrunyan I can source clean accurately sized images of these devices. 

With respect to the list. It only shows the best selling devices for a quarter. It does not necessarily represent the total market share of devices being used in the world. Hence it may be helpful for us to use the same list as Figma, who has already most likely invested the time and research to narrow down on this list.

**Comment by shrunyan** [comment]
related https://github.com/zesty-io/manager-ui/issues/461

**Comment by zcolah** [comment]
![iPad Pro](https://github.com/zesty-io/manager-ui/assets/22625919/e10ff8b3-764a-4106-b623-2c491bb1b49c)
![iPhone 14 Pro](https://github.com/zesty-io/manager-ui/assets/22625919/9caabd12-d82e-4400-bc12-822a5899f982)
![iPhone 14](https://github.com/zesty-io/manager-ui/assets/22625919/598fbf22-0da6-466c-870c-94ce641befba)
![Pixel 7](https://github.com/zesty-io/manager-ui/assets/22625919/70f9dac5-5bed-4efa-8cda-abb3f74929a8)
