### ISSUE TITLE
Favicon: Select Favicon appears when a non image file has been selected

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1493]
**Bug:** 
Right now when a user selects a a non-image asset as a favicon they get an error similar to this. 
<img width="215" alt="Screen Shot 2022-11-03 at 2 02 04 PM" src="https://user-images.githubusercontent.com/22625919/199833442-f1384e92-bbfb-443b-99de-e71485aca7f3.png">

**Solution**
Only show image files in the options available to select as a favicon in the media selector.

**Comment by shrunyan** [comment]
Of note is the favicon test is failing at the moment

**Comment by shrunyan** [comment]
related https://github.com/zesty-io/manager-ui/issues/1463
