### ISSUE TITLE
Media App: Add Sort and Filters to Search Experience

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1545]
**Solution Description:** 
When a user makes a search in the Media app, we should allow them to filter their results. For example if a user searches for the word "Hike", they should be able to see the results, sort them, and filter them down by file type and date. 

Key Things to note: 
- Add a line that mentions how many matches are found once a filter is applied
- When a search is made, no filters should be applied by default
- Please ensure the filter parameters get added to the page URL when applied

**Figma**
https://www.figma.com/file/pBgVbMZSItzqRYcEXg2lhe/Media-App?node-id=2509%3A206356&t=Nykf7ek42MJnJ7Ql-1

**Comment by rjpals** [comment]
Closed by #1593
