### ISSUE TITLE
Media App: Filter Pill Height is Taller Than It Should be

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1587]
**Problem**
The filter pills have grown in size since one of the most recent updates. They have become 40px in height instead of 28px. This makes them look very odd and off. 

**Solution**
You can see the sizing of the filter especially the height and padding in the Figma spec here: https://www.figma.com/file/pBgVbMZSItzqRYcEXg2lhe/Media-App?node-id=2253%3A171851&t=PwKhUTRk0YJqHRkE-1

**Comment by JacobDiazCruz** [comment]
This is the view when I updated it to 28px. @agalin920 Should we update the height of the dropdown fields as well? And are we doing it on the theme level? Or should I just adjust it manually on the component?

![Image](https://user-images.githubusercontent.com/40680430/206091623-2e966a9a-cec7-4e9e-bef9-62f3d2cca9d9.png)
