### ISSUE TITLE
Sub-app navigation drawer

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#164]
**Is your feature request related to a problem? Please describe.**
Below 2000px we render a "constrained" view. We have media queries which alter the layout of less dominant elements. 

**Describe the solution you'd like**
When the manager-ui is displayed in a constrained viewport (sub 2000px) we should switch the sub-app navigation to be drawers. That is they can be "closed" so the content of the nav is out of view. This will allow for more working space within the sub-applications.

In combination with on hover of the global menu opening that sub-app nav drawer we will conserve space while keeping quick access to deeper app views.

**Describe alternatives you've considered**

**Additional context**

**Comment by shrunyan** [comment]
How this is implemented could have an effect on this request https://github.com/zesty-io/manager-ui/issues/454

**Comment by d88naimi** [comment]
Should be resolved with this PR: https://github.com/zesty-io/manager-ui/pull/932
