### ISSUE TITLE
Settings: full instance purge button

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#169]
**Is your feature request related to a problem? Please describe.**
If a site wide setting casuses issues it's necessary to trigger a full instance cache purge to correct the problem Currently this is only possible by publishing code. In many cases publishing could be undesirable.

**Describe the solution you'd like**
An instance action, located in settings would make sense, to trigger a full instance cdn cache purge. It would purge based on the instance ZUID surrogate key.

This is a significant action which should only be available to `admin` and `owner` roles.

**Describe alternatives you've considered**

**Additional context**
A customer recently experienced a CSP issue. After changing the setting they need to purge all instance pages. This required manual support intervention as we do not currently offer an option to do this. _Besides a code publish but in an emergency response that's the last thing you want to do as it can insert large amounts of uncertainty._

Depending on the size of an instance and it's current traffic load a full purge could have significant performance impacts on page loading. We should include a warning with this button which indicates the potential severity of the action.

**Comment by shrunyan** [comment]
We can use the existing cloud function to implement this behavior. Connect with me for details on it's usage.

**Comment by shrunyan** [comment]
I think this button should exist in the instance dropdown at the top right of the app shell

**Comment by kakoga** [comment]
👍 as customers have asked for this in the past too.
