### ISSUE TITLE
Side Navigation: Visual QA Roll Up

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1751]
**Describe the bug**
Hi Jacob, 
Please see all the visual QA issues for the side navigation bar listed as comments in the Figma file here: https://www.figma.com/file/5tJk3UE7xa9cGF7TYbIYWQ/Side-Navigation?node-id=478%3A29849&t=C9EfSqU6WjPm5waM-1

I will add a separate ticket for the visual QA for the fly out.

**Comment by JacobDiazCruz** [comment]
Yup, my bad
