### ISSUE TITLE
New Nav Layout UI Bugs / Errors

### ISSUE THREAD

**Issue by ardeay** [zesty-io/manager-ui#1769]
**Error with Image in bottom user Account Image**
![image](https://user-images.githubusercontent.com/729972/214706366-0e49dd09-2f58-48cd-9f6c-12cd2a436ce5.png)

**Floating tab issues**
Content, Schema, Leads, SEO->Redirects, Apps, Settings need a `border-top: 1px white solid` in the respective app
![image](https://user-images.githubusercontent.com/729972/214706879-7fc4e79e-48c0-4102-b22a-2d55b4028c4f.png)

**Comment by shrunyan** [comment]
https://github.com/zesty-io/manager-ui/pull/1748/commits/19b87b952f22e631a7930e0bc2feea63ed1aabe0
https://github.com/zesty-io/manager-ui/pull/1748/commits/f0d90edf5419fb425523c4416bd6225a9944557a
https://github.com/zesty-io/manager-ui/pull/1748/commits/a4c89653d4020bf3d6f50ec1f8e258660b069f27
https://github.com/zesty-io/manager-ui/pull/1748/commits/60c9052f162c2118b2e25e5c9746b336f6171838
