### ISSUE TITLE
Search App: VQA Round 2 

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1776]
Hi Ryan, 
Please look at the Figma for VQA Round 2: https://www.figma.com/file/esyXLuQc0ugHqaUgybpAfP/Search-App?node-id=933%3A61433&t=9gVA0gOOzW73DDVT-1

Please check that each ticket issued is resolved and notify me on Slack once you complete VQA Round 2 when it has shipped to stage or is ready for my review on dev.

**Comment by shrunyan** [comment]
PR was merged
