### ISSUE TITLE
Media App: Folders not appearing in the list view

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1777]
**Describe the bug**
The folders in this folder appear in the grid view. 

<img width="1440" alt="Screenshot 2023-01-26 at 3 00 25 PM" src="https://user-images.githubusercontent.com/22625919/214969824-cdcaeb81-203d-488e-b559-2f95a426a713.png">

However they do not appear in the list view when they should be appearing. 

<img width="1440" alt="Screenshot 2023-01-26 at 3 00 58 PM" src="https://user-images.githubusercontent.com/22625919/214969878-e3de235b-28fe-4f9c-9f52-db88637b9387.png">

**To Reproduce**
1. Go to https://8-aaeffee09b-7w6v22.manager.zesty.io/media/folder/1-70f2a7b-0i2db
2. Click on the list view icon

**Comment by JacobDiazCruz** [comment]
Upon checking on my prod instance, it seems like the sub folders are displayed.
![image](https://user-images.githubusercontent.com/40680430/217393844-e50dcb2d-1e2e-4de1-8f32-1d58e5d41ed1.png)

@zcolah can you give me access on your instance?

**Comment by JacobDiazCruz** [comment]
@agalin920 Got it, sorry I didn't noticed the folders having the globe icon indicating that it's a bin.
