### ISSUE TITLE
"Ctrl + S" do not work as "Save" in the style settings.

### ISSUE THREAD

**Issue by b-estevez** [zesty-io/manager-ui#1788]
Trying to change some new settings in the styling however you need to scroll down at the bottom part and hit the save button in order to apply the changes.

![image](https://user-images.githubusercontent.com/55866499/216110912-0a0c7855-885c-4452-a1fd-4249db480077.png)

I think its better that "ctrl + s" or "cmd + s" should work as a save for better experience to the users.

![image](https://user-images.githubusercontent.com/55866499/216111944-b37a5579-ef30-4eb6-953b-affd7569c9cc.png)

**Comment by rjpals** [comment]
Closed by #1793
