### ISSUE TITLE
My Accounts in user dropdown leads to old Accounts UI 

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#1818]
![Screenshot 2023-02-14 at 1 02 12 PM](https://user-images.githubusercontent.com/9896546/218820300-9cf53c3a-a3d8-4070-a0f2-db256f542cb1.png)

All reference to the old Accounts interface need to be updated

**Comment by theofficialnar** [comment]
@giseleblair can this be closed? New app shell ui should resolve this
