### ISSUE TITLE
Schema: Delay showing the field description pop up by 1 second 

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1854]
**Is your feature request related to a problem? Please describe.**
Currently when a user tries to insert a new field they immediately see the pop up describing each field type. This can be a bit overwhelming per se. See Video for reference
https://www.loom.com/share/ce210bb7e18a4fc7802fe94515b57cd4

**Solution**
Delay showing the field description pop up by 1 second

**Comment by theofficialnar** [comment]
This is actually quite weird since I have added a delay on this on the code but for some reason it automatically shows up when you immediately hover over the next item. I'll take a closer look at this and see if there's maybe something else I need to change.
