### ISSUE TITLE
Schema: Disable ability to select a cell (and remove orange border) in the All Models Table

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1856]
Disable ability to select a cell. Please ensure this orange border does not show up when the row is selected. 

See Screenshot below for reference. 

<img width="1164" alt="Screenshot 2023-02-23 at 3 23 25 AM" src="https://user-images.githubusercontent.com/22625919/220892661-fe1508c8-dd90-4a71-8449-4a9ac150afa8.png">

**Comment by zcolah** [comment]
This table is not an input. I would argue for now to remove the focus state.

**Comment by theofficialnar** [comment]
Theme update pr: https://github.com/zesty-io/material/pull/70
