### ISSUE TITLE
Schema: Edit Field Modal gets triggered despite a user not clicking on a field

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1877]
**Describe the bug**
Currently when a user copies a field's ZUID from the more(3 dots) dropdown menu and clicks out, it triggers the edit field modal for that field whose ZUID was copied. 

See video: https://www.loom.com/share/67495cb33944429ea4b5d4c6e3f369fb

**Solution**
This should not happen.

**Comment by theofficialnar** [comment]
This has been fixed on https://github.com/zesty-io/manager-ui/pull/1869
