### ISSUE TITLE
Accounts Login: Update to show all SSO Buttons

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1889]
**Describe the bug**
If a user goes to https://accounts.zesty.io/login they see the following screen which does not have the google or github sign in options.  

<img width="1440" alt="CleanShot 2023-02-28 at 22 16 11@2x" src="https://user-images.githubusercontent.com/22625919/222059884-38ba137d-e84b-492d-9f5f-37a52815845a.png">

**Solution**
Please redirect user to https://www.zesty.io/login/ as that has all the login options

**Comment by shrunyan** [comment]
This will be resolved once legacy accounts is sunset
