### ISSUE TITLE
Schema: Theme Change - update the colors of the the scrollbar color in all dropdowns

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1901]
**Problem**
Below is an image of the current look of a scroll bar in a dropdown select. As you can see these greys are a lot darker than the colors we are using for the rest of the scrollbars in the schema design and media. 

<img width="272" alt="CleanShot 2023-03-02 at 02 09 23@2x" src="https://user-images.githubusercontent.com/22625919/222398346-edacdc08-21a8-4d90-a921-33b296682d4d.png">

**Solution**
Make the bar color Grey 300, and make the scroll area color Grey 100.

**Comment by theofficialnar** [comment]
Theme override on PR: https://github.com/zesty-io/material/pull/70

**Comment by theofficialnar** [comment]
Hi @zcolah, wouldn't setting it theme-wide also affect the scrolbar on legacy components like code? idk, if that's what you want. let me know
