### ISSUE TITLE
Schema: Do not allow models to self reference themselves

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1902]
**Describe the bug**
Assume I am in the articles model. I click on add new field and select one to one relationship field. Currently the system will allow me to set the reference model as the articles model itself. Basically we are self referencing. I do not think this should be possible or allowed. See video for more context: https://www.loom.com/share/b3aed0b4add84afc88935fc18d078060

**Solution**
Do not show the model the one to one relationship field belongs to in the dropdown to prevent self referencing.

**Comment by giseleblair** [comment]
@agalin920  not a user error, models can reference themselves. That functionality should not be removed
