### ISSUE TITLE
Navigation Link Text is blank after duplicating a single page model with One to One field as the first field item of the schema

### ISSUE THREAD

**Issue by b-estevez** [zesty-io/manager-ui#1934]
Instance Zuid: 8-ac91ad86e9-txcblw

Scenario:

Duplicating the Homepage and naming it as "Another Page" (Click screenshots for bigger view)

<img src="https://user-images.githubusercontent.com/55866499/225963208-7178a2ef-bd42-4451-9ac8-f3ffff8b8827.png" width="400px">
<br>
<img src="https://user-images.githubusercontent.com/55866499/225963916-ae6da1b5-c3f7-465f-9584-145e118034ce.png" width="400px">
<br>
<img src="https://user-images.githubusercontent.com/55866499/225964354-924fc2a9-60eb-4cb3-8114-b3813a8d6320.png" width="400px">

Upon duplicating the Single Page Model, there is no content item created that can be view on the "Content view"
<img src="https://user-images.githubusercontent.com/55866499/225965021-09358653-9533-4dae-89a2-a5cf198f2709.png" width="300px" height="300px">

But I tried creating an item and manually adding a path part value: "another-page"
<img src="https://user-images.githubusercontent.com/55866499/225965711-f59c79db-93ac-4b8d-afd2-aa81b8bd014e.png" width="300px">

After creating the item, the Navigation Link Text is "blank":
<img src="https://user-images.githubusercontent.com/55866499/225966256-7c188a33-021d-47d3-85c4-b7a4b76300ae.png" width="300px">

Meaning the user will still put a navigation link text value manually from the "SEO & Meta" section.

Enhancement:

I consulted to @giseleblair  and suggested that **giving a Navigation Link Text value** should be part of the duplication process. The default value will base to the actual name of the duplicated model.

📝Please take note that all existing fields in the duplicated model are one to one field.

Kindly let me know if you need more details regarding this thread.

**Comment by b-estevez** [comment]
I see, but I think it will give a confusion to the user especially if there are already plenty of content items.

I can find the content item of the duplicated model even with a blank **Navigation Link Text value** its because I am already familiar with the interface, but for new users I think it will be a weird experience.

Maybe using the duplicated model's name as a default Navigation Link Text value can help user to identify the content item of the duplicated model e.g. (Another Page as **another-page**).

But this is just a suggestion or enhancement for the model duplication interface based on my experience in the UI.

**Comment by giseleblair** [comment]
@agalin920 when the model being created is a single page model, the manager will create an item off of that model. This includes when a model is duplicated

**Comment by theofficialnar** [comment]
Hi @giseleblair and @agalin920 I just tried running old schema locally to verify this functionality and it seems like duplicating a single page model **doesn't** automatically create a content item, I had to manually create one after duplicating the model. It only automatically created a content item when creating a totally new model - which is what's currently missing on new schema that seems to me is what needs to be addressed.

Attaching a video of how I duplicated a model on old schema

https://user-images.githubusercontent.com/28705606/226526721-60cae731-a4d3-4118-9000-27ca5838915a.mp4

**Comment by theofficialnar** [comment]
> @theofficialnar also create on duplication please. But thanks for pointing it out

Yeah, I'm working on it, I'm getting an error from the api that I'm not really sure what it means when automatically creating an item during duplication though.

**Comment by theofficialnar** [comment]
> @theofficialnar ah ok well you can just make the content item for the duplicated model before the fields are copied over then
> 
> 1. Duplicate model button click
> 2. Create new model from base
> 3. Create new model item
> 4. Add fields to new model

Ah right, yeah I'll give that a try

**Comment by theofficialnar** [comment]
@agalin920 @giseleblair, there's something odd I found while working on this issue.

For the parentZUID, the old schema is using the ZUIDs from `/env/nav` while on new schema we're using the ZUIDs from `/content/models`. On the new schema automatically creating a model with a parentZUID that was from `/content/models` throws an error, whilte it works fine if the parentZUID is from `/env/nav`.

ZUIDs from `/env/nav` are a mix of 7- and 6-

Looking for some inputs whether or not I should revert back to how old schema does the parentZUID which is from `/env/nav`.

**Comment by b-estevez** [comment]
> Hi @b-estevez @giseleblair and @agalin920 I just tried running old schema locally to verify this functionality and it seems like duplicating a single page model **doesn't** automatically create a content item, I had to manually create one after duplicating the model. It only automatically created a content item when creating a totally new model - which is what's currently missing on new schema that seems to me is what needs to be addressed.
> 
> Attaching a video of how I duplicated a model on old schema

Yep this works perfectly fine since the first field item in the screen recording example is a **Text** which automatically copy its text value to the **SEO & Meta** fields. 

But if you try to duplicate a single page model that has **Image** or **One to One relationship** as being the first field, the Navigation Link Text value will be blank.  

![image](https://user-images.githubusercontent.com/55866499/226593919-4263da13-c116-4729-94be-df3776a765be.png)

**Comment by giseleblair** [comment]
@agalin920 how is the model label generated? Is this user input?
