### ISSUE TITLE
headless models as parents

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#1936]
It looks like the UI's content navigation tree now displays nested headless models properly. Please allow for headless models to be selected in the Schema app. 
The feature was removed as requested [here](https://github.com/zesty-io/manager-ui/issues/1895) when the UI did not display nested headless sets properly in the content nav tree. This looks to have been updated and now the functionality should be brought back in the UI.

**Comment by giseleblair** [comment]
Now that the UI displays the nested items in the navigation tree, the user does expect to be able to nest any and all models. This is not an enhancement since it is part of the api's current capabilities.

**Comment by markelmad** [comment]
> 

Didn't find any validation/restriction check for this one for both CM and item.

**Comment by markelmad** [comment]
> I believe adding a 6- as a parentZUID to a single page model rejects the create item from that model api call. We might need to filter these based on model type.
> 
> @markelmad Can you verify that for me?
> 
> cc: @theofficialnar

Didn't find any validation/restriction check for this one for both CM and item.
