### ISSUE TITLE
"All Instances" button not working in new Global Nav

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/manager-ui#1992]
![Screen Shot 2023-04-13 at 11 21 23 AM](https://user-images.githubusercontent.com/22846981/231849431-7c391f9a-058d-43ce-9743-caf1aab67ae1.png)
Hi all, when I click "all instances" I expect a new tab to open to the accounts instances view, but nothing happens when I click it.

**Comment by theofficialnar** [comment]
Hi @chloespilotro, this is by design. It's supposed to just be like a list subheader that let's users know what's below it are all the instances.

cc @zcolah
