### ISSUE TITLE
Incorrect ZUID shown in Content Item page

### ISSUE THREAD

**Issue by markelmad** [zesty-io/manager-ui#1996]
**Describe the bug**
On the Content Item page, the ZUID shown in the info panel is the content model's ZUID instead of the content item's ZUID.

**Expected behavior**
The info panel should show the content item's ZUID, not its content model's ZUID.

**Screenshots**
![image](https://user-images.githubusercontent.com/3361467/232158437-f4239b18-e0c1-4d51-bf2d-e4ef30225ce9.png)

**Comment by theofficialnar** [comment]
It was always already like this in production even before the content repaint was released. I made no logical changes during the repaint. @shrunyan would like to get your clarification if we should be making this change or not? I guess it sort of makes sense that this should be the content item zuid, but currently the tooltip says that this is the content model zuid.

**Comment by zcolah** [comment]
This should be content item ZUID for sure. Should have never been the model ZUID. Pls move forward with making this change asap.

**Comment by giseleblair** [comment]
This has not been resolved, while the item zuid is displayed the content model is copied when the user clicks on the zuid

**Comment by theofficialnar** [comment]
@giseleblair Seems like I forgot to actually also update the function that handles the copy zuid. 😓
