### ISSUE TITLE
Global Search Feedback

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#2056]
Would like to be able to search by just a user. Currently requires adding a keyword to activate the search button.
![image](https://github.com/zesty-io/manager-ui/assets/208819/f7832e8a-05f7-4268-9e94-cfb5751d558c)

Would like to be able to deselect a dropdown selection. Currently once selected you can only clear with "Clear All"
![image](https://github.com/zesty-io/manager-ui/assets/208819/299ed1aa-2c67-448f-b02f-8508ff4eec44)

Once on the advanced search results screen it becomes confusing on how to search for a different keyword. The primary global search input fades into the other options that are now displayed. It is also physically separated from the other filters, making it unclear these work in tandem. If you hit the far right clear button it kicks you out of the search results view. If you change the keyword in the global input it resets all the filters.
![image](https://github.com/zesty-io/manager-ui/assets/208819/6edb34da-415a-426d-be78-e02ca9563ade)

The advanced search model does not have a top right close icon. Not sure why this differs from all the other modals

**Comment by zcolah** [comment]
**Would like to be able to search by just a user. Currently requires adding a keyword to activate the search button.**
@shrunyan @theofficialnar Is it possible to send a user name to the search end point and get a list of all the content items made by them back? Can we also quickly filter models and code files on the front end by user name?
