### ISSUE TITLE
Warning when attempting to store react.element in IDB

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#2068]
**Describe the bug**
Console warning when attempting to write a 'react.element' to IDB
 
**To Reproduce**
1. Open dev console
2. Go to http://8-f48cf3a682-7fthvk.manager.dev.zesty.io:8080/content/6-a1a600-k0b6f0/7-a1be38-1b42ht/analytics?datePreset=last_14_days
3. See error

**Expected behavior**
Do not attempt storing react components in IndexDB

**Screenshots**
![image](https://github.com/zesty-io/manager-ui/assets/208819/098e163c-c32e-40c0-837c-f2aa67a36e35)

**Additional context**

**Comment by theofficialnar** [comment]
Can't seem to replicate this anymore using the master branch and on prod.

**Comment by theofficialnar** [comment]
Hey @agalin920 , can you confirm if this has been resolved?
