### ISSUE TITLE
Search: Advanced Filter Modal - Allow a user to search just by the user name

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2079]
**Problem**
Would like to be able to search by just a user. Currently requires adding a keyword to activate the search button.
![image](https://github.com/zesty-io/manager-ui/assets/22625919/887e95f0-f40b-49bc-ad69-ca68255a8559)

**Solution**
Allow a user to enter only a user name and no keyword and return a list of content items and models made by them. 

Note: We cannot return media items and code files due to the limitations of our end points.  Hence they are excluded.

**Comment by theofficialnar** [comment]
Same issue raised on #2056
