### ISSUE TITLE
Search: Advanced Filter Modal should reflect the pre-applied filters on search results

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2081]
**Problem**
Assume a user opens the search bar
1. Searches for a phrase "Headless" and hits enter
2. They see the search results
3. They apply a created by, date, and resource type filter 
4. They open the advanced filter modal, and only see that keyword added in. They do not see the filters. This requires them to re-enter the filters again and is also not consistent with the filters they just applied. 

<img width="1440" alt="CleanShot 2023-06-22 at 07 48 35@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/05fe0c86-9f47-4564-8dd8-2d1e2c57b6dc">

**Desired Solution**
The selected filters should be already selected as options in the advanced filter modal like this. 
<img width="1440" alt="CleanShot 2023-06-22 at 07 49 14@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/3f011e55-4741-46c5-9d0f-b06b14042c82">

**Comment by theofficialnar** [comment]
As discussed, this functionality shall only apply when the user is already in the search page with filters applied
