### ISSUE TITLE
Search: Update Default Options to Be "Any Type, Any Time, Any One, Any Language" for the filters in the Advanced Filter Modal

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2084]
**Problem**
Would like to be able to deselect a dropdown selection. Currently once selected you can only clear with "Clear All"
![image](https://github.com/zesty-io/manager-ui/assets/22625919/16b4f075-c5f3-4677-af25-5c298e783e57)

**Solution**
To allow a user to deselect their dropdown selection aka clear it, we will add in an option to filter by Any Type, Any Time, Any One, and Any Language. This will be the default option selected when a user opens the Advanced Filter Modal (if no filters were already applied from the Search Results page). 

Figma: https://www.figma.com/file/esyXLuQc0ugHqaUgybpAfP/Search-App?type=design&node-id=650%3A55295&t=317OBA4FiGF1EmTw-1

**Comment by theofficialnar** [comment]
Resolves an issue raised in #2056
