### ISSUE TITLE
Side Navigation Bar: Open Instance Switcher Sub Menu and Domains Sub Menu on right on hover instead of on click

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2088]
**Is your feature request related to a problem? Please describe.**
Currently enterprise users find it tiring that they have to click on Switch Instance / Domains  in the Instance Menu to see all of the menu contents. Further they would be prefer it opened to the right on hover similar to how Slack does it. 

**Solution**
When a user hovers on the Switch Instance option or the Domains option in the Instance Menu, the menu will open to the right. Designs are in Figma: https://www.figma.com/file/5tJk3UE7xa9cGF7TYbIYWQ/Side-Navigation?type=design&node-id=1001%3A61081&mode=design&t=rLiFIX2DuDGpaxIY-1

**Note:** 
1. Pay close attention to how the sub menu is overlayed on top of the main menu with a little offset. 
2. Also the back button has been intentionally removed as the menu now flys out on hover to the right vs replacing the main menu

**Comment by shrunyan** [comment]
To clarify this is just sub-menus that would be activated by hover? The initial primary menu would still be activated by clicking on the instance name/icon?

**Comment by zcolah** [comment]
@shrunyan @theofficialnar 
Only the sub-menus need to be activated by hover. 
The initial primary menu will continue to be activated by click.

**Comment by theofficialnar** [comment]
Just need @shrunyan's confirmation if I can prioritize this after wrapping up global search phase 7 which should be pretty much done next week - just finishing up the vqa tickets.

**Comment by shrunyan** [comment]
@theofficialnar yes, please place this ticket in next on your board and we will reconfirm after the current project finishes.
