### ISSUE TITLE
Schema: Add Delete Model and Duplicate Model Buttons 

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2093]
**Problem**
Users have reported that they go to the Info Tab when they want to delete or duplicate a model. However they are unable to find any option that allows them to do the same. 

![CleanShot 2023-06-26 at 12 37 47@2x](https://github.com/zesty-io/manager-ui/assets/22625919/503c2412-8b15-4a62-89d9-0f989b91e16d)

**Describe the solution you'd like**
We have added two buttons: a Delete Button, and a Duplicate Model button to the model details section in the Info Tab to help solve for this problem. See the Figma User flows here: https://www.figma.com/file/jeRhgXqNsP7Bmd2YoQLA4z/Schema-App?type=design&node-id=2303%3A227924&mode=design&t=GbfNzWvfT04t8E3o-1

<img width="1364" alt="CleanShot 2023-06-26 at 12 36 10@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/d34c5b9b-c444-4985-b1a9-c9921ae7253c">

**Comment by shrunyan** [comment]
Currently these actions exist in the model flyout. Do we plan on leaving them there or should those be removed?

**Comment by zcolah** [comment]
These actions should remain in the fly out.
