### ISSUE TITLE
Global Search: All Search Results are not showing up

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2099]
**Describe the bug**
When I search for ".png" via the search bar in Media this is the list of results I get. 

<img width="1440" alt="CleanShot 2023-07-03 at 15 58 09@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/ae9139b0-6da7-4db3-b85d-6b1d3c6a39cb">

However when I search ".png" via the Global Search bar, there are no media type search results. See screenshot. 
<img width="1377" alt="CleanShot 2023-07-03 at 15 58 43@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/5d9881f2-cb60-461d-b335-f301906adb94">

I am not sure why the results are not matching, but what I am assuming is that potentially the media app is adding the extension to the filenames and then searching maybe? Andres could be able to help with this bug as he worked on search in Media.

**Comment by theofficialnar** [comment]
@zcolah, if you're seeing this on either prod do note that Global Search Phase 6 - which includes media results - has not been deployed to prod yet and if it's on stage then the version on stage has been replaced with a different branch that does not contain the code changes in phase 6 yet.
