### ISSUE TITLE
Content: SEO Tab Revamp

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2118]
# Intro
## Visual Improvements
The SEO tab will now leverage our new Material Design Language. 

![Image](https://github.com/user-attachments/assets/224f06e5-20b5-4148-8b06-c1a71b721a1f)

# UX Improvements
### Social Media Previews
Users will now be able to see Social media previews for twitter, facebook, linkedin, and Google. 

![Image](https://github.com/user-attachments/assets/b7b35350-68b6-4db7-954a-e81045802a6b)

### AI Assistant
Users will now be able to generate a Meta Title and Meta Description using our AI Assistant
![Image](https://github.com/user-attachments/assets/687a5c0d-232d-42ac-8452-1ebf5e4b4713)

# Figma
https://www.figma.com/design/Oc42SSkzPDozxO7zZRCUJT/SEO-Tab?m=dev&node-id=67-61597&t=SMAW6kZuY5z43cmS-1

**Comment by finnar-bin** [comment]
Note:
- og_image field needs to be hidden from the content item fields

**Comment by zcolah** [comment]
# Task 1: Handling case of blank og_image field
In the case of the og_image field of a content item being blank, WebEngine should fall back to: 
- displaying the first image file from a field with the word image in it's label 
- if there is no field with the word image in it's label, it should then display the first image file it finds in the content item

This Web Engine resolution order fix needs to be done by @jjaguilar08 and Randy. Once this fix is made it needs to be tested by @finnar-bin. 

# Task 2: Rendering Image in Preview Card
The image in the preview cards in the SEO tab should use the same OTF parameters, Web Engine applies for the social media previews for Twitter Card and Open Graph (Facebook, Linkedin). Google can be left as is. This is not a top priority.

**Comment by zcolah** [comment]
# Tooltip text for the following AI Assistant Inputs

1. Tone: Set the desired style and mood of the generated text
2. Word Limit: Set a word limit to control the length of the generated text
3. Language: Set the language in which you’d like the text to be generated.
