### ISSUE TITLE
Apps: App Sidebar Revamp

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2195]
# Intro 
This is a revamp of the sidebar in Apps. It will mimic the visual style of the sidebar seen in Content. 

One key change is that the browse apps button has been removed and replaced with a marketplace tab and plus button in the top right corner of the sidebar. 

The Add Button and Marketplace Tab should open up: https://www.zesty.io/marketplace/apps/

The collapsing, resizing, and expanding of the sidebar should mimic that in the content, reports, schema, and media apps. 

I have also created an empty state for when there are no apps installed. 

# Figma Design: 
https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/App-Navigation?type=design&node-id=406%3A180249&mode=design&t=l1lRip2Is6LwwexE-1

**Comment by theofficialnar** [comment]
Will also close #1989
