### ISSUE TITLE
Okta users redirected to non-SSO login screen when their session expires

### ISSUE THREAD

**Issue by gtllien** [zesty-io/manager-ui#2209]
When a user authenticates using Okta and and their session expires, their login prompt does not include a signIn option for Okta.

Request to include SSO option when users get into the login screen.

**Comment by shrunyan** [comment]
This is not possible with the Okta SSO flow. As there is meta information that is specific to that users organization in Okta which is required to login. This is why Okta logins must be initiated from within Okta.
