### ISSUE TITLE
Global: Hitting Escape on a Modal makes the button used to trigger it focussed. This is not desired. 

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2254]
**Describe the bug**
If I click on a button to open a modal, and click escape once the modal opens, it then proceeds to highlight (focus) the button I clicked. This is not an experience desired and there is no way to escape the focus mode outside of clicking on something else. 

Unsure if this is a bug or request as this has never been requested as a functionality prior to this. Also open to hear opinions on what should be done here. In no way do we need to immediately fix this. 

See Loom for more details. https://www.loom.com/share/fa1236e8818242199280871fbf212ed7

**Comment by theofficialnar** [comment]
@zcolah by default mui dialogs seem to restore focus on the previously closed element when esc is used to close the dialog. One way I can see us making sure this doesn't happen is by setting `disableRestoreFocus` of the dialog to true theme-wide?

**Comment by zcolah** [comment]
On deeper investigation, I discovered that this functionality is default for accessibility purposes. Hence I am closing this ticket.
