### ISSUE TITLE
Navigation: Clicking on the Update Favicon Modal Backdrop not allowing me to exit modal

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2255]
**Describe the bug**
Clicking on the Update Favicon Modal Backdrop not allowing me to exit modal. 
![CleanShot 2023-09-12 at 18 27 06@2x](https://github.com/zesty-io/manager-ui/assets/22625919/3b75377b-8b53-4e79-8557-ac85c2bd2c6b)

**Expectation**
It should let me exit the modal.

**Comment by theofficialnar** [comment]
I don't think this modal was designed to support close on background click to begin with since it's not using mui components

**Comment by zcolah** [comment]
Understood
