### ISSUE TITLE
Preview page icon visible in dataset content item leading to 404 page when access

### ISSUE THREAD

**Issue by gtllien** [zesty-io/manager-ui#2262]
**Describe the bug**
From customer: Attempting to access previews for Dataset items via the new icons leads to 404s

**Expected behavior**
I believe the preview icon should be disabled or hidden for dataset content items since it has no routing

**Screenshots**
![null-value](https://github.com/zesty-io/manager-ui/assets/112954373/3797d982-a734-4b0c-8e7d-06cc1f51f0ff)

Slack thread: https://zestyiodevs.slack.com/archives/C1RRP2B0A/p1694654659542529

**Comment by zcolah** [comment]
Please hide this behavior for dataset items
