### ISSUE TITLE
View Site Generators API option available in dataset content item leading to null/no object returned

### ISSUE THREAD

**Issue by gtllien** [zesty-io/manager-ui#2263]
**Describe the bug**
When accessing Dataset items via “View Site Generators API” it's returning null/no object

**Expected behavior**
“View Site Generators API” option is not applicable for dataset content items since it has no routing, thus object returns null. It's best hidden or disabled for datasets

**Screenshots**
![site-generators-null (1)](https://github.com/zesty-io/manager-ui/assets/112954373/e8eccb0c-1f78-470d-a1e8-b82be98c17d1)

toJSON is null/no object returned:
![image](https://github.com/zesty-io/manager-ui/assets/112954373/443e50fa-f0f3-4d4e-ba5f-15b44f661549)

Slack thread: https://zestyiodevs.slack.com/archives/C1RRP2B0A/p1694654747496059

**Comment by zcolah** [comment]
Please hide this
