### ISSUE TITLE
Code: Escape Key closes suggestions dropdown (instead of leaving file)

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2269]
# Problem
A developer has reported: 
"When I type CSS, I get suggestions in a dropdown. The problem is if I hit escape on my keyboard while typing, it kicks me out of the file and puts me into the file I was in last, instead of just removing the dropdown."

This is extremely frustrating for each developer as in any other IDE clicking the escape key on the keyboard only exits the suggestions dropdown (when it is open). 

# Solution
To be consistent with the other IDE experiences out there, we will do the following: 

1. The escape key should not close a code file in any scenario. 

2. When the code suggestions dropdown is open, the escape key must close the dropdown. 

See Loom Video explaining the solution.

**Comment by theofficialnar** [comment]
@zcolah I'm assuming the suggestions dropdown being referred to here is the global search suggestions?

**Comment by zcolah** [comment]
@theofficialnar this video will help, not sure why the old loom link did not paste https://www.loom.com/share/4a87b9c7699e43629f8556fe682472ce
