### ISSUE TITLE
Global Nav: Instance Favicon Not Displaying

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2270]
**Describe the bug**
The Instance Favicon of this Instance is Not Displaying despite it being set to this image: https://td6p1p78.media.zestyio.com/Logo.jpg

<img width="1439" alt="CleanShot 2023-09-19 at 14 32 03@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/6512795c-e55f-40cb-9b14-88bbd86c3b26">

**Expected behavior**
The Instance Favicon of this Instance should display.

**Comment by theofficialnar** [comment]
Looks like this is related to this issue #2267
