### ISSUE TITLE
Unexpected dropdown behavior

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#2273]
**Describe the bug**
2 issues to note with the Global Nav > Instance flyout -> Switch Instance -> Dropdown

1. When pressing the down arrow to select an option from the list it closes the switch instance dropdown and arrows through it's parent instance flyout
2. The switch dropdown closes when hovering off our changing window selection(i.e. in your OS tabbing to another application). This is opposite to how the parent instance flyout behaves. I would expect both parent flyout and child dropdown to remain open until clicked out of.

**Expected behavior**

**Screenshots**
![image](https://github.com/zesty-io/manager-ui/assets/208819/29da6f14-91d4-4f28-a15b-993da9b002b2)

**Additional context**

**Comment by zcolah** [comment]
Issue 1 should be resolved as per the expected behavior defined by @shrunyan.
 
For Issue 2 I need more context. @shrunyan may you please provide a Loom video of Issue 2 in Zesty along with an example of expected behavior in an application of your choice.
