### ISSUE TITLE
Multi-page content item in bottom row not visible in view

### ISSUE THREAD

**Issue by gtllien** [zesty-io/manager-ui#2278]
**Describe the bug**
In a multi-page content list view (of >10 content items added), the bottom row is not visible in view; horizontal scroll-bar is also not visible

**To Reproduce**
1. Go to Instance > Content, and access a Multi-page content (list with >10 content items added) 
2. Scroll down to the bottom part of the list, and check the content item in the last/bottom row is not visible in view

**Expected behavior**
Muti-page content item in bottom row should be visible when a user scroll down to the bottom of the page; horizontal scroll bar should also be visible

**Screenshots**
resolution: 1600x861
![image](https://github.com/zesty-io/manager-ui/assets/112954373/a243d3e4-38c1-4ff5-940b-e0e6ace02b4a)

See also video:
https://github.com/zesty-io/manager-ui/assets/112954373/99bbcb10-6c31-4f98-ae02-27d332a78fb8

**Comment by theofficialnar** [comment]
@agalin920  Can't we adjust the height of the table so that all the items are shown and just set the scrollbar height and width to 0px?

**Comment by gtllien** [comment]
@agalin920 It's not just an issue with the scrollbar - as I pointed out the "**content item in bottom row not visible in view**"
As you can see in the highlighted screenshot, the arrow pointed to a content of an item at the bottom row but it's not visible in the screen. 
As for the horizontal scrollbar, I mentioned it since the width is cut-off and there's no way for the user to see the full view esp. if they have a lot of columns/fields added (even if the sidebars are already collapsed).
