### ISSUE TITLE
Unpublished & Delete Content

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#228]
**Is your feature request related to a problem? Please describe.**
The unpublished and delete content buttons require selecting dropdown to get to main action. I believe this is an extra click that is unnecessary 

**Describe the solution you'd like**
remove dropdown click to get to unpublished and delete button 

**Describe alternatives you've considered**
"More space for click" on drop down triangle https://pulse.heartbeat.ua/design-tips/components

![Screen Shot 2020-10-13 at 9 45 14 AM](https://user-images.githubusercontent.com/22800749/95890711-f3876b00-0d38-11eb-8644-fa48ffcce49f.png)

**Comment by shrunyan** [comment]
These actions have drastic effects. As such we have intentionally minimized there presence so a user has to be very explicit about taking the actions.
