### ISSUE TITLE
Content: Update WYSIWYG to latest version of Tiny MCE

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2312]
# Intro 
Our current version of Tiny MCE is [TinyMCE 5.10.4](https://www.tiny.cloud/docs/changelog/?utm_campaign=editor_referral&utm_medium=help_dialog&utm_source=tinymce). 

We will now upgrade it to the latest version - [Version 6.7](https://www.tiny.cloud/blog/tinymce-latest-version/#:~:text=TinyMCE%20latest%20version%3A%206.7,well%20as%2021%20bug%20fixes.). 

# Helpful Links to learn more about migration

1. https://www.tiny.cloud/pricing/
2. https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/
3. https://www.tiny.cloud/docs/tinymce/6/
4. https://www.tiny.cloud/docs/tinymce/6/upgrading/
5. https://www.tiny.cloud/long-term-support/

# Functionalities We Must Retain to maintain parity

1. Zesty CMS must save the content in the WYSIWYG every time a user saves a content item.  The CMD+S and CTRL+S key should trigger the content item save even on the wysiwyg. 
2. Insertion of Media from the Zesty Media App should still be possible (when the user clicks on the image icon button)
3. Special Embeds of instagram youTube and twitter frames should be supported

# Plugins
When updating it please install the following plugins: 

## Free Plugins to Install

1. Advanced Lists: https://www.tiny.cloud/docs/tinymce/6/advlist/
4. Auto Link: https://www.tiny.cloud/docs/tinymce/6/autolink/
6. Auto Resize: https://www.tiny.cloud/docs/tinymce/6/autoresize/
7. Edit Source Code: https://www.tiny.cloud/docs/tinymce/6/code/
8. Code Sample: https://www.tiny.cloud/docs/tinymce/6/codesample/
9. Character Map: https://www.tiny.cloud/docs/tinymce/6/charmap/
10. Emoticons: https://www.tiny.cloud/docs/tinymce/6/emoticons/
11. Full Screen: https://www.tiny.cloud/docs/tinymce/6/fullscreen/
12. Quick Toolbars: https://www.tiny.cloud/docs/tinymce/6/quickbars/
13. Image: https://www.tiny.cloud/docs/tinymce/6/image/
14. Insert Date/Time: https://www.tiny.cloud/docs/tinymce/6/insertdatetime/
15. Link: https://www.tiny.cloud/docs/tinymce/6/link/
16. Lists: https://www.tiny.cloud/docs/tinymce/6/lists/
17. Media: https://www.tiny.cloud/docs/tinymce/6/media/
18. Search and Replace: https://www.tiny.cloud/docs/tinymce/6/searchreplace/
19. Table: https://www.tiny.cloud/docs/tinymce/6/table/
20. Visual Blocks (Need to Test Further): https://www.tiny.cloud/docs/tinymce/6/visualblocks/

## Premium Plugins to Install

1. Power Paste: https://www.tiny.cloud/docs/tinymce/6/introduction-to-powerpaste/
2. Advanced Code Editor: https://www.tiny.cloud/docs/tinymce/6/advcode/
3. Advanced Table: https://www.tiny.cloud/docs/tinymce/6/advtable/
4. Advanced Typography: https://www.tiny.cloud/docs/tinymce/6/advanced-typography/
6. Enhanced Media Embed Plugin: https://www.tiny.cloud/docs/tinymce/6/introduction-to-mediaembed/
7. Link Checker: https://www.tiny.cloud/docs/tinymce/6/linkchecker/
8. Page Embed: https://www.tiny.cloud/docs/tinymce/6/pageembed/
9. Spell Checker Pro: https://www.tiny.cloud/docs/tinymce/6/introduction-to-tiny-spellchecker/
10. Auto Correct: https://www.tiny.cloud/docs/tinymce/6/autocorrect/

# UI Updates

1. Remove File Dropdown Menu from Menu bar (above Toolbar) 
2. Remove Text Color
3. Remove Font Size 
4. Remove Line Height

## Minimum Height
The minimum height of the WYSIWYG Input will become 560px instead of the current minimum height. This is because users have reported that the default height is extremely large. Ideally in the future I would love to explore potentially setting both a minimum and maximum height. 

## Toolbar Buttons
When updating TinyMCE, please try to make the button order resemble the button order shown in the screenshot below. Please note that there may be some buttons not accounted for in the screenshot. I am not sure what those may be. Please reach out to me to discuss them further when you reach this stage.  

![image](https://github.com/zesty-io/manager-ui/assets/22625919/b098d785-4646-40d9-80fd-936c6ba86497)

## Floating Toolbar
Please try to make the button order resemble the button order shown in the screenshot below for the floating toolbar.  
![image](https://github.com/zesty-io/manager-ui/assets/22625919/1a60470c-2ac4-4ca8-a3be-d0ac4fb04af5)

## Theme Skin
Update the theme to use the skin in this zip file. This matches the Zesty style. 
[Zesty.zip](https://github.com/zesty-io/manager-ui/files/13365896/Zesty.zip)

## Font
- Make the font of the Content in the WYSIWYG to be Mulish. 
- If possible please make the font in the pop up and dropdown menus is also Mulish. 

# Loading Experience
The current WYSIWYG editor takes time to initialize and load up causing a layout shift which confuses. In order to avoid this, we should allocate space and show a loading spinner (if possible). 

# Image Size Testing
In the current version of Tiny MCE image widths stretch outside the bounds of the WYSIWYG input. Please test in the updated version this is not the case and that images and videos inserted stay within the bounds of the WYSIWYG input. Ideally all images should have the same width as that of the WYSIWYG input. 

If the test shows that the image issue is not resolved, the resolve it within this ticket itself unless it is extremely complex. If it is a complex issue , then please make an individual ticket on the product roadmap to resolve this issue right after shipping the updated version. Please see Loom for more context: https://www.loom.com/share/da7d40f94f4440d9be54615142445a02

This is a critical improvement to make. As two customers have come forth with similar feedback on the current image rendering experience: > "If the design intends to compress the fields, we need to compress the images within the fields to see the whole image."

# Copy Paste Testing
Copy Text from [this Google Doc](https://docs.google.com/document/d/1jdtEjMAAYft20tK_VR0oPTJwFuPSPjWBjVYeURwU528/edit?usp=sharing) and see if the formatting carries forward and renders correctly. 

# Reference Images of Before vs After 

## Before

With Toolbar Closed
![CleanShot 2024-01-23 at 03 46 25](https://github.com/zesty-io/manager-ui/assets/22625919/e9a8956e-60d0-47ca-92d4-9f7bfe848a08)

With Toolbar Expanded
![CleanShot 2024-01-23 at 03 46 38](https://github.com/zesty-io/manager-ui/assets/22625919/4ee6a81a-35a7-4d65-84b6-7569da6d5ea0)

## After 

![CleanShot 2024-01-23 at 03 47 29](https://github.com/zesty-io/manager-ui/assets/22625919/e019eddc-9186-4af7-a60a-4887afe45899)

**Comment by theofficialnar** [comment]
@shrunyan is this ready to be worked on? I remember you mentioned something about needing to check about the costing for this last week.

**Comment by zcolah** [comment]
@theofficialnar May you please hide or remove the Plugins page. Also there is no margin/on the top and bottom of the modal. May you please add 20 px margin at the top and bottom. 

![CleanShot 2023-12-07 at 12 52 32](https://github.com/zesty-io/manager-ui/assets/22625919/91fd38ef-b65a-4a5f-87cd-a65ddeb95953)
