### ISSUE TITLE
Schema: Model Empty State is missing padding on left

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2313]
**Problem** 
See image for more context
![CleanShot 2023-10-26 at 14 55 08@2x](https://github.com/zesty-io/manager-ui/assets/22625919/cfe7ef2e-c095-4b3e-a1bc-067d0f02fc42)

**Solution**
32px margin/padding on left

**Comment by theofficialnar** [comment]
@zcolah Heads up I've already fixed this on a different PR that got recently merged. Should be on prod once it's deployed by Stuart.

https://github.com/zesty-io/manager-ui/pull/2310

**Comment by theofficialnar** [comment]
As discussed, will be closing this ticket as the issue has been resolved on a prior PR.
