### ISSUE TITLE
Content: WYSIWYG Rendered Output is not Matching the Input 

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2320]
# Problem
A user has reported: "Sometimes the Heading formatting doesn't get reflected on the text when an article is published.
For eg - in the screenshots below 'Understanding Website Migrations and CMS Migrations' is H2 formatted in the editor and shows up as Bold Paragraph text."

## Manager UI Screenshot
![image](https://github.com/zesty-io/manager-ui/assets/22625919/9b8b7ba3-b1e0-4953-bfc5-507f286fc8b3)

## Website Screenshot 
Notice how "Understanding Website Migrations and CMS Migrations"  does not look like a Heading 2!!! This should not be the case.
![image](https://github.com/zesty-io/manager-ui/assets/22625919/772f9bf3-9d05-44c2-a4a7-504ba1beea5f)

# Relevant Links
Manager UI URL: https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-45a908-qfw88c/7-a8ade5c8c4-nczbw7
Website URL: https://www.zesty.io/mindshare/migrate-website-new-cms/

**Comment by shrunyan** [comment]
Closing this as a non-issue. As the WYSIWYG is properly using an `H2` tag, although there is also a `strong` tag wrapping the text. The CSS written for the website is causing this effect.

![image](https://github.com/zesty-io/manager-ui/assets/208819/ce76ca5c-6b0f-4a9f-8aef-413869a9b43d)
