### ISSUE TITLE
Content: Single Page Analytics UX Enhancements

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2321]
# Intro 
We will be making the following UX enhancement updates to Single Page Analytics: 

![image](https://github.com/zesty-io/manager-ui/assets/22625919/85e92a2e-24fc-4606-acdb-111bc90b4d8d)

## **1. Revise Data Fields Presented in the User Breakdown Donut Chart to cause lesser confusion**
a. Blue Donut: New (Light Blue) and Returning Users (Dark Blue) for the last 14 Days
b. Grey Donut: New (Light Grey) and Returning Users (Dark Blue) for the prior 14 days

### Tooltips Text
Note: Please also look into the line spacing issue. It should be 10px font size and 14px line height. 

**New Users for the Last 14 Days:** 
New users are users who have never visited your website or app before

**Returning Users for the Last 14 Days**
Returning users are users who have never visited your website or app before

**New Users for the Prior 14 Days:** 
New users are users who have never visited your website or app before

**New Users for the prior 14 Days**
Returning Users for the prior 14 Days

## **2. Replace Sessions with Views  in the Metric Bar and in the Line Chart** 
It is a more appropriate metric to track for an individual page. Sessions is more appropriate when analyzing an entire website's traffic vs a single page's traffic.

### Tooltip Text
Views
A pageview is defined as a view of a page on your site that is being tracked by the Analytics tracking code. If a user clicks reload after reaching the page or navigates to a different page and then returns to the original page, then this is counted as an additional page view.

## **3. Replace Avg. Duration with Average Engagement Time in the Metric Bar and in the Line Chart** 
It is a more appropriate metric to track for an individual page. Session Avg. Duration is more appropriate when analyzing an entire website's traffic vs a single page's traffic.

### Tooltip Text
Average engagement time
Average engagement time is the average time that your website was in focus in a user's browser or a mobile app was in the foreground on a user's device. 

## **4. Bugs and Enhancements**
Please check in with Andres on this while resolving. 

1. Tooltip does not appear on hover for the line chart unless the user hovers over a version 
2. Green dot does not appear on line chart to show a published version despite me publishing the item
3. All published versions are not appearing as green dots

See Loom: https://www.loom.com/share/31792a359943425a8d946072af1b904d

See Design: 
![CleanShot 2023-11-29 at 18 41 57](https://github.com/zesty-io/manager-ui/assets/22625919/bc8c7676-2f90-4509-b09e-043169543b53)

**Comment by theofficialnar** [comment]
Check with Allen and Stuart, need to get analytics merged together - marketplace and in-app analytics. In-app needs to be put into the marketplace, then will be used as a widget.

**Comment by theofficialnar** [comment]
@zcolah here are some feedback towards some concerns you've raised

> Green dot does not appear on line chart to show a published version despite me publishing the item
Only the "Today" date filter shows analytics data up to the current day, all other filters eg. Last 14 days, Last 7 days etc. will not include data of the current day

> All published versions are not appearing as green dots
I've checked this out and the versions do appear but you need to change the number of days in the date filter since there are some versions published that are not within the data you're currently looking at. Like in the screenshot below, latest publish was Nov 7 which is beyond the default "last 14 days".
![Image](https://github.com/zesty-io/manager-ui/assets/28705606/aeb7298e-a2d1-4e79-952c-cf51e063a74d)
