### ISSUE TITLE
Content: Publish Confirmation Modal

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2322]
# Problem 
Users sometimes publish items unintentionally by clicking the publish button. This leads to major announcements getting released before they should which is a big business problem for our users. 

# Solution 
Hence, when the system tries to publish a modal, we will now trigger a modal that confirms with the user that they wish to publish the content item. See screenshot below.  

![image](https://github.com/zesty-io/manager-ui/assets/22625919/2a0dd22c-f73b-403b-a1ad-67be8227b700)

# Figma 
https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=3107-221171&mode=dev

**Comment by theofficialnar** [comment]
@zcolah what's the experience like if the user clicks on "save and publish" then they cancel out of the publish popup? Will the changes be saved even if they cancel out of this popup?

**Comment by zcolah** [comment]
**@zcolah what's the experience like if the user clicks on "save and publish" then they cancel out of the publish popup?** 
The changes should be saved. They are only cancelling out of publishing.
