### ISSUE TITLE
Global: In App Announcement: Improve Image Resolution

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2373]
**Describe the bug**
The product screenshot is blurred in the app announcement. Please increase the resolution at which this image is rendered. Is it possible to potentially render it at it's original quality or at least 80% of it's original quality. 

![CleanShot 2023-11-30 at 18 46 56](https://github.com/zesty-io/manager-ui/assets/22625919/a0c84bcb-eebf-4249-9962-afae8c7494c6)

**Comment by zcolah** [comment]
https://developer.fastly.com/reference/io/quality

**Comment by zcolah** [comment]
https://kfg6bckb.media.zestyio.com/Content---Edit-Content-Tab-with-DUO-Mode.jpg?quality=85

**Comment by shrunyan** [comment]
There is no explicit modification of quality happening with that image. The current specified dimensions are width=560 & height=300. What would you like them to be?

**Comment by zcolah** [comment]
@shrunyan Made a Loom covering your comment 
https://www.loom.com/share/d1893f942d5e4cb7be553827e9e87fa7?from_recorder=1&focus_title=1

**Comment by shrunyan** [comment]
We need to include at least one dimension value otherwise we will be sending a much larger image than needed.

**Comment by zcolah** [comment]
@shrunyan Unfortunately adding either dimension value significantly impacts the resolution/crispness of the image. See my investigation in this video done here: https://www.loom.com/share/ea12e715e4694595954b0823da69f835

Yes the file size is larger if we do not use dimensions and only set the file size quality=85. However it also gets us our desired outcome which is a crisp image which is not blurred.

**Comment by shrunyan** [comment]
I have watched the loom. The addition of a dimension does not automatically degrade image "crispness". Having a 560x300 resolution of an interface is going to look blurry. There is just to many small visual details. A 1280px width image is going to look much better but is a 1/3 the size of the original. 

_example file size responses of unbound, 560 and 1280_
![image](https://github.com/zesty-io/manager-ui/assets/208819/d293ba76-d266-4e15-90f5-0bddab85d85c)
 
This image must have at least one dimension set and ideally the UI area where it is displayed would match that same dimension.

**Comment by zcolah** [comment]
@shrunyan may we move forward with using the width set as 1280px then if possible?

**Comment by shrunyan** [comment]
@zcolah sure. @theofficialnar lets use `1280px` as the dimension.
