### ISSUE TITLE
Content: Saved By Text is Not Appearing in the Tooltip

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2394]
**Describe the bug**
I saved a content item but when I hover over the saved text it does not show that I saved the item. It is just blank after the word "by"

![CleanShot 2023-12-12 at 11 17 04](https://github.com/zesty-io/manager-ui/assets/22625919/251ea0ad-2f21-4563-a5cf-4ce0807d9b47)

**Comment by zcolah** [comment]
@agalin920 


1. Go to https://8-f48cf3a682-7fthvk.manager.dev.zesty.io/content/6-a8bae2f4d7-rffln5/7-fc84f2b8f9-j25dz2
2. Make a change to the content 
3. Hit Save
4. Then Hover over the Saved Button and you will notice the user name does not appear in the tooltip

**It seems like my user name does have a name btw**


 
![CleanShot 2023-12-22 at 04 51 10](https://github.com/zesty-io/manager-ui/assets/22625919/c63b77ba-30fe-4721-80d6-0e69bdc0855a)

**Comment by giseleblair** [comment]
@markelmad this is not expected behavior. Please file this as a bug. We should save logs on all API actions

**Comment by zcolah** [comment]
@giseleblair this is part of a larger conversation that needs to be had regarding the Audit Log for a content item not reflecting correctly. Will be discussing the same with Randy and Stuart today. 

@giseleblair has any customer spoken up about this issue?

**Comment by giseleblair** [comment]
@zcolah there has not been any customer feedback on this.

**Comment by zcolah** [comment]
@agalin920 this issue seems to be occurring only on version 1 as we do not have a "Created" audit log. Potentially a workaround could be that we check the [created by] on the item's API and use that value as any user who creates the item is technically the user who saved the item in it's v1 state.

**Comment by zcolah** [comment]
@giseleblair @agalin920 made an issue for it https://github.com/zesty-io/manager-ui/issues/2466

**Comment by markelmad** [comment]
@agalin920 I can also confirm the bug. Still investigating why creating an item doesn't show the user's name when hovered despite the API saving the user's ZUID in the db column `action_by_user_zuid`. Moreover, when updating an item, for the 'hover' to show the name, it requires an API purge _**(or by saving another item)**_. I will also investigate if this can be done on the API side.

**Comment by zcolah** [comment]
@agalin920 if there is no created activity record for the content item, may we take the following approach: 
> We check the [created by] on the item's API and use that value as any user who creates the item is technically the user who saved the item in it's v1 state.

Also we can use this as a temporary workaround if @markelmad is busy and needs more time to investigate this issue
