### ISSUE TITLE
Content: SEO Fields are slower than expected (lots of lag)

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2412]
**Describe the bug**
A customer has reported: 

> Some of the fields have become extremely laggy such as the ones in SEO 
> The text I type into the fields does not appear in real time
> This was not an issue until the recent update
> See screenshot below 

![image](https://github.com/zesty-io/manager-ui/assets/22625919/8dbf8fea-6784-4d49-a04e-20b1fb435d18)

**Solution**
Please look into what is causing the fields to behave slow and restore it to it's original performance.

**Comment by theofficialnar** [comment]
Note: Updating Navigation Link Text and Meta Title seems to be triggering a lot of re-renders
