### ISSUE TITLE
Content: Improved Microcopy for Notifications

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2416]
# Task 
May the Front End Team please provide a spreadsheet document of all the notifications that can get displayed in the Content App and what end points/actions are associated to it? 

**The columns in the spreadsheet should include:** 

1. The notification message copy 
2. Type: Success / Warning / Error
3. Which part of the Content App does the notification appear in?
4. What triggers the notification to show?
5. Why does it get triggered? 

Once I receive this spreadsheet, I will revise the copy to follow best practices for UX Writing and also work on making the language more consistent and educational for the user and create an issue on our roadmap for the same.

**Comment by glespinosa** [comment]
@zcolah Please use this sheet for your reference on the microcopy for notifications
https://docs.google.com/spreadsheets/d/1Cwd_1UdHjgakbxS22xbRMA1bY5Cx9P9da-qpw_352O8/edit#gid=0
Let me know if you have any questions. Thank you

**Comment by zcolah** [comment]
@glespinosa 
Thank you for this list. In the same way, may you also give me a list of the microcopy for the notifications in the Schema, Search, Redirects, Media apps?

**Comment by glespinosa** [comment]
@zcolah sure will do

**Comment by glespinosa** [comment]
@zcolah I updated the sheets. Have a question regarding `Search` what do you mean on that is it the global search?

**Comment by zcolah** [comment]
Yes I mean it is on Global Search

**Comment by glespinosa** [comment]
status: waiting on Randy's approval

**Comment by zcolah** [comment]
**@glespinosa Here is the Spreadsheet with the Updated Microcopy**
https://docs.google.com/spreadsheets/d/1SWff7pdgzsJsmSyIRnTz8fKRuA6KudB_1SDGUe6mOos/edit?usp=sharing

- [ ] Please remove the notifications for the ones where it is mentioned not needed and update the icon where necessary.
- [ ] Please note in the case of the new notification messages with two lines, please use the notification style shown below. 

![image](https://github.com/zesty-io/manager-ui/assets/22625919/f1139f6c-cd98-4455-85c9-62b60eb3418c)

**Comment by glespinosa** [comment]
> **[@glespinosa](https://github.com/glespinosa) Here is the Spreadsheet with the Updated Microcopy** https://docs.google.com/spreadsheets/d/1SWff7pdgzsJsmSyIRnTz8fKRuA6KudB_1SDGUe6mOos/edit?usp=sharing
> 
> * [ ]  Please remove the notifications for the ones where it is mentioned not needed and update the icon where necessary.
> * [ ]  Please note in the case of the new notification messages with two lines, please use the notification style shown below.
> 
> ![image](https://private-user-images.githubusercontent.com/22625919/323731036-f1139f6c-cd98-4455-85c9-62b60eb3418c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzkwMzAsIm5iZiI6MTcxMzQ3ODczMCwicGF0aCI6Ii8yMjYyNTkxOS8zMjM3MzEwMzYtZjExMzlmNmMtY2Q5OC00NDU1LTg1YzktNjJiNjBlYjM0MThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDIyMTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyODU4MDczZDU2YTIxNThiNmQ1OGFjYzczNzQ1ZjkwODdhYmRkMDMwZTlmMWFkYWJhYmZhZDFiMjdhNDgxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4quNGJ6S6PIqbBIEu0sJi0__ncmgXEGAmQPpn-e94xo)

Thank you @zcolah . Noted on this , will apply these changes on my end

**Comment by glespinosa** [comment]
quick question @zcolah are these considered two lines notification where it will follow the ui above  ? 
![image](https://github.com/zesty-io/manager-ui/assets/44116036/ece1d788-6f57-4166-88df-d8c986f9647b)

**Comment by zcolah** [comment]
@glespinosa Yes these are the two line type. They will follow this style of UI. 

![image](https://github.com/zesty-io/manager-ui/assets/22625919/e3045053-f309-4886-9fbe-ad2586a62c48)

**Comment by glespinosa** [comment]
@zcolah can i have a sample value for this  [Item Nav Link Text] ?

**Comment by glespinosa** [comment]
@zcolah regarding the Action button in the UI above, what action should we assign on it?

**Comment by glespinosa** [comment]
@zcolah I updated all the message notification in the code base on the google sheets provided.

**Comment by zcolah** [comment]
Hello @glespinosa 
No Action needs to be assigned.

**Comment by zcolah** [comment]
@glespinosa Thank you for updating the messages. I will check and test this project when it reaches Beta Release.
