### ISSUE TITLE
Schema: Create Model Modal - Enter Key should trigger Create Model Button

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2430]
**Is your feature request related to a problem? Please describe.**
![CleanShot 2024-01-09 at 02 54 30](https://github.com/zesty-io/manager-ui/assets/22625919/e71d967a-969a-4113-969f-e7ca0f4903de)

**Comment by jomarmontuya** [comment]
Model creating test breaking

**Comment by jomarmontuya** [comment]
Debugging Flaky tests cases

**Comment by jomarmontuya** [comment]
Related tickets -> https://github.com/zesty-io/manager-ui/pull/2535
