### ISSUE TITLE
Schema: Add Field Tooltip Styling has multiple issues

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2432]
**Describe the bug**
See Figma: https://www.figma.com/file/jeRhgXqNsP7Bmd2YoQLA4z/Schema-App?type=design&node-id=156%3A19677&mode=dev&t=a98lfZnXcRNl88Wk-1

![CleanShot 2024-01-09 at 04 24 13](https://github.com/zesty-io/manager-ui/assets/22625919/748c541d-3f07-4d74-8978-77ba91667013)

**Comment by jomarmontuya** [comment]
@zcolah  I requested you an access to figma file 

Thank you!
