### ISSUE TITLE
Schema: Rename Integer Field Type to Number Field Type

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2443]
**Problem**
Please rename the Integer Field to a Number Field as it can support float numbers as well. In many areas we are already calling it a number field but in some places we are calling it as an Integer Field. 

**Solution**
In those cases please rename it. I have highlighted them down below. 

- [ ] ![CleanShot 2024-01-09 at 23 49 26](https://github.com/zesty-io/manager-ui/assets/22625919/f8ecabd5-9d8f-419d-a1f7-840146ce1ecc)

- [ ] ![CleanShot 2024-01-09 at 23 51 02](https://github.com/zesty-io/manager-ui/assets/22625919/80c25238-db78-4840-be70-9364d3560ca4)

- [ ] ![CleanShot 2024-01-09 at 23 51 41](https://github.com/zesty-io/manager-ui/assets/22625919/291b6c56-7b75-489f-8649-c1612082a37b)

- [ ] Do the same for the Edit Integer Field Modal as well.

**Comment by markelmad** [comment]
I'll go with these changes (integer to number) since the underlying datatype really is a float in the first place.
