### ISSUE TITLE
Content: Typing experience is laggy when multiple fields are present

### ISSUE THREAD

**Issue by finnar-bin** [zesty-io/manager-ui#2463]
**Describe the bug**
When editing a content item with multiple fields, typing experience is very laggy

**To Reproduce**
1. Go to a content item with multiple fields
2. Start typing on any field
3. See issue

**Expected behavior**
Typing should not be laggy

**Screenshots**
[content-fields-lag.webm](https://github.com/zesty-io/manager-ui/assets/28705606/a4079004-c83b-4022-9b05-f632ff032164)

**Comment by theofficialnar** [comment]
Note: All of the fields present are re-rendering even if the user is not actively editing that field, may need to change the component composition to prevent this

**Comment by theofficialnar** [comment]
- [x] Move state closer to components using them
- [ ] Verify that saving and errors are still working
- [ ] Verify that item create still works fine
