### ISSUE TITLE
Content: No Fields Have Been Added Screen appears for Content Items that have fields

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2490]
**Describe the bug**
The No Fields Have Been Added Screen appears for Content Items that have fields! See Loom: 
https://www.loom.com/share/731170c4a53e4bf48530a293108e4e49
![CleanShot 2024-01-30 at 00 35 13](https://github.com/zesty-io/manager-ui/assets/22625919/011a65e9-5cb0-47f9-8497-1091ed7f8428)

**Desired Solution**
This screen should only appear Content Items that have NO fields.

**Comment by theofficialnar** [comment]
@zcolah should it show some kind of loading indicator while it's initially trying to load the fields? If yes, what kind of loading indicator should we put in?

**Comment by zcolah** [comment]
@theofficialnar there are already multiple loading indicators present before this screen. Adding one more will be potentially make the experience seem even more slow. Hence as @agalin920 recommended we will show no loading indicators here.
