### ISSUE TITLE
Media: Upload Modal Became Unresponsive after uploading 5 images

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2491]
**Describe the bug**
Upload Modal Became Unresponsive after uploading 5 images. See two loom videos. 

1. https://www.loom.com/share/406f14b814d64bb7a5de5ceb709878e9
2. https://www.loom.com/share/8beea6afda9549a18648e8e5f853a706

Instance URL: https://8-da92b5d8e6-hvp4w4.manager.zesty.io/media/folder/2-11136d45-7d4h2v

**Comment by finnar-bin** [comment]
@zcolah has this happened again? Tried replicating it across various instances and I am unable to replicate it, even tried uploading 5+ images and also in the create content item.

**Comment by zcolah** [comment]
No this has not happened again. Let us close this ticket until this issue happens again.
