### ISSUE TITLE
Content: Edit Content Item Page - Control P / Command P Shortcut to Publish Item does not work 

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2492]
# Bug
The following two functions defined the spec of the edit content item page are not working. Please fix them.  

1. A user should be able to save and publish an item if they use Control P or Command P | [Figma](https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=588%3A214419&mode=dev&t=Rbz5dOZRKSfbOcnG-1)
2. A user should be able to publish an item if they use  Control P or Command P | [Figma](https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=505%3A154455&mode=dev&t=Rbz5dOZRKSfbOcnG-1)
 
# Reference Articles
https://www.robin-drexler.com/2015/07/07/overriding-default-browser-shortcuts/
https://support.mozilla.org/kn/questions/1367908#:~:text=You%20can%20use%20the%20Browser,want%20to%20disable%20or%20override.

**Comment by glespinosa** [comment]
@zcolah I tried Ctrl+P without changing so far in the code it brings a modal isn't this the expected behavior?


https://github.com/zesty-io/manager-ui/assets/44116036/e476fe9b-51f1-4a27-95da-1146509426eb

**Comment by glespinosa** [comment]
@zcolah I think it's working fine also , I ask darwin to try it in their machine. Is cmd command working fine on your end?

**Comment by zcolah** [comment]
@glespinosa it is now working. Closing this issue.

**Comment by zcolah** [comment]
@glespinosa Command P is opening the print dialog. Can you look into why? 
![CleanShot 2024-04-05 at 21 30 24](https://github.com/zesty-io/manager-ui/assets/22625919/75549e2d-bb4c-4358-bca6-0c342ef1f05b)

**Comment by glespinosa** [comment]
@zcolah Upon checking I think because you're mouse is in focus on a textfield , I don't know if this issue existed previously. Try focusing it outside the textfield
