### ISSUE TITLE
Media: Upload Modal - Title does not become plural

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2495]
**Describe the bug**

If 1 file is uploaded the title should say "1 File Uploaded"
Else the title should say "[N]" Files Upload .... e.g. 5 Files Uploaded

See screenshot below. 

![CleanShot 2024-01-30 at 02 08 51](https://github.com/zesty-io/manager-ui/assets/22625919/fbbc8368-66a7-4a00-bd2b-9a6629796ada)

**Comment by glespinosa** [comment]
@zcolah we made some discussion on the label for this one instead of bug , this should be tag as enhancement cause it's already existing within the app but just need some improvements for that label. If there's no problem changing the bug label I'll proceed changing on that. Thank you
