### ISSUE TITLE
allow for document template creation in Wysi UI

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#250]
**Is your feature request related to a problem? Please describe.**
Every month I need to use the same template to create an article. Since this is on a monthly basis, I don't remember all of the formatting and stylization that the article requires, so I need to go back to earlier articles and copy/paste the it into the new article to maintain consistency. 

**Describe the solution you'd like**
I would love a way to create a simple, savable template in the wysiwyg that I could recall each time I need to create my article. While I am currently using HTML to make a template that will not be a viable solution for all users, so I'm thinking that users should be able to format a doc in the wysiwyg and save it as a template - instead of say - needing to add in HTML code to create a template.  

**Describe alternatives you've considered**
My current solution is an html file on my desktop - I copy and paste its formatting into the editor in the wysiwyg. 

**Additional context**

**Comment by shrunyan** [comment]
Possibly we could allow addition of content as a field setting. Field settings are stored as JSON. @crzestyio what size limitations would we have around storing a large string in a JSON structure at the database? Any additional concerns or questions that come to mind around implementing something like this?

**Comment by shrunyan** [comment]
Implementing this should be fairly straight forward. 

1. Add new textarea on WYSIWYG schema fields in the schema app
2. Allow string content which gets added to the field settings JSON
3. Save field setting
4. Update content editor to preload field setting if it exists and the fields value is blank

This could work for quite a few field types, pre-filled content from field settings, such as; text, textarea, markdown. Initially I think just the WYSIWYG field would be all we do.

**Comment by kakoga** [comment]
I would love the flexibility to do this on a field as necessary. 
getting into the weeds but could something like this also go towards giving the user the option to have placeholder text in a field? 
I know that right now we use tooltips created in Schema but just a thought of something else that might be beneficial in that arena.

**Comment by shrunyan** [comment]
Closing in favor of https://github.com/zesty-io/manager-ui/issues/619 which will allow for this feature
