### ISSUE TITLE
Content: SEO Tab - Title Bar reflects Published State for a Second when the user tries to save item

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2503]
# Bug
## What's Happening
1. I updated the SEO Meta Parent for a Content Item. 
![CleanShot 2024-01-30 at 22 02 48](https://github.com/zesty-io/manager-ui/assets/22625919/2c0d0855-5c5e-4abf-b95c-be099eb028ea)

2. I clicked on Command S on my keyboard to Save the Item. The Title Bar reflects Published State for a Second. 
![CleanShot 2024-01-30 at 22 03 17](https://github.com/zesty-io/manager-ui/assets/22625919/587414ed-b2d7-40d0-a776-6e4920fa485b)

3. It then correctly updates to show that it is not published and only Saved
![CleanShot 2024-01-30 at 22 03 30](https://github.com/zesty-io/manager-ui/assets/22625919/8e45a907-293c-45f3-ba69-1c8372c34eb7)

## See Loom
https://www.loom.com/share/ff14f89cc2ee4ea19fa03a63efea1f90

# Solution Desired
The title bar should only display that an item is published if it is actually published. In this case it was not published and hence the titlebar should not have displayed that for a second also.

**Comment by glespinosa** [comment]
@zcolah From my observation every time I set it to v1 then the save that issue above occurs. Still checking on what cause this


https://github.com/zesty-io/manager-ui/assets/44116036/4792aaff-734f-470e-afea-7496a93d498c

**Comment by glespinosa** [comment]
> [@zcolah](https://github.com/zcolah) From my observation every time I set it to v1 then the save that issue above occurs. Still checking on what cause this
> 
>  screencast-8-aaeffee09b-7w6v22.manager.dev.zesty.io_8080-2024.02.07-10_47_51.webm

@theofficialnar can you guide me why there's an issue why when I select v1 it's partially showing the publish, it gives the user that the item is being publish while the user is currently saving it. I'm currently looking in the ItemEditHeaderActions.tsx upon checking on it the conditions looks fine unless you pick the v1. pls see above for reference vid

**Comment by theofficialnar** [comment]
> > [@zcolah](https://github.com/zcolah) From my observation every time I set it to v1 then the save that issue above occurs. Still checking on what cause this
> > screencast-8-aaeffee09b-7w6v22.manager.dev.zesty.io_8080-2024.02.07-10_47_51.webm
> 
> @theofficialnar can you guide me why there's an issue why when I select v1 it's partially showing the publish, it gives the user that the item is being publish while the user is currently saving it. I'm currently looking in the ItemEditHeaderActions.tsx upon checking on it the conditions looks fine unless you pick the v1. pls see above for reference vid

Have you tried checking out how the publish state is being determined? If I remember correctly it's probably inside /shell/store/content.js

**Comment by zcolah** [comment]
@glespinosa @theofficialnar 
https://www.loom.com/share/1f4df31755184301a454a45cede60b7f

**Comment by zcolah** [comment]
@theofficialnar @glespinosa I want to follow up on this ticket. Any progress?

**Comment by theofficialnar** [comment]
@glespinosa any update on what's going on with this ticket?
