### ISSUE TITLE
Media App: Move and Delete Buttons Disappearing after files are selected and re-appear on page refresh for a while

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2510]
**Describe the bug**
Move and Delete Buttons Disappearing after files are selected and re-appear on page refresh for a while

1. I went to the Media App and selected a few files 
2. I tried to select them to move them 
3. But the buttons disappeared
4. I refreshed the page and the buttons reappeared
5. Then again they disappeared for a while and reappeared on page refresh (not captured in the video)

See Loom: https://www.loom.com/share/5274919bd03048c394d639e25f914396

**Solution**
The Move and Delete Buttons should always be present once a user selects 1 or more files.

**Comment by giseleblair** [comment]
@zcolah can you please take a look at this and help reproduce

**Comment by zcolah** [comment]
Closing this issue as it cannot be replicated.
