### ISSUE TITLE
Cannot toggle and save boolean field value to NO

### ISSUE THREAD

**Issue by arzljames** [zesty-io/manager-ui#2530]
**Describe the bug**
When a boolean field is defined in the schema, it cannot toggle and save the value to **NO** within the specific item. However, you can save it when viewing all the items from the content.

**To Reproduce**
1. Go to Schema
2. Click on 'Create Model' (any models)
3. Go to the newly created model and add/define a 'Boolean' field
4. Go to content and toggle the boolean to NO
5. See error

**Expected behavior**
Expected to be able to toggle and save the boolean field with YES (1) or NO (0)

1. Toggled with **YES** and click save
expected result: _"show_field": "1"_
![image](https://github.com/zesty-io/manager-ui/assets/70579069/1fa3df59-c016-4364-a7be-c04eb61bbc87)
![image](https://github.com/zesty-io/manager-ui/assets/70579069/47185370-e3cb-4f66-acf4-fbb721e6ea7f)

2. Toggled with **NO** and click save
expected result: _"show_field": "0"_
![image](https://github.com/zesty-io/manager-ui/assets/70579069/e416c0f1-8a30-4340-892a-cdf95562781b)
![image](https://github.com/zesty-io/manager-ui/assets/70579069/5b596bac-c9b6-44d9-b46e-8c41023374b8)

**Screenshots**
https://www.loom.com/share/540edcaeceb94c73b321ae35ecd65bc5

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 121.0.6167.140 (Official Build) (64-bit)

**Comment by arzljames** [comment]
Also want to add this screenshot @agalin920 that you can toggle it to NO (all items view) and the result is "0"
![Screenshot 2024-02-06 054940](https://github.com/zesty-io/manager-ui/assets/70579069/12e11ebd-8d5a-4198-8264-397ea1b8bcd7)
![image](https://github.com/zesty-io/manager-ui/assets/70579069/a7ca8a4d-6f5d-4e64-ae86-de2b25513a6c)

**Comment by giseleblair** [comment]
> @giseleblair with our attempt to make null values consistent. Do we want to keep save No as "0"

Do not save as "0", save it as the option that has been set by the user
