### ISSUE TITLE
Include tooltips and description for the user to have a clear idea on what specific buttons do.

### ISSUE THREAD

**Issue by Sammieboy00** [zesty-io/manager-ui#2542]
A customer pointed this out and since they were new to the interface, they were hovering on buttons and did not know what those buttons do and they specifically said that tooltips would help them.

Create tooltips when buttons are being hovered upon.

Here is a sample screenshot of the specific buttons that the client had no idea on what the specific buttons do.

![tooltips](https://github.com/zesty-io/manager-ui/assets/141294382/645759cf-e41e-44e5-83b6-e333b49354ff)

**Comment by zcolah** [comment]
Hi Sammie
Can you take a Loom video to show that no tool tips appear? We have added
tool tips for each of these and hence are asking for a Loom.

**Comment by Sammieboy00** [comment]
[Attached is the loom video](https://www.loom.com/share/72837b568bcd4048841078420ffc6ea4?sid=659c64b3-c02d-4ca8-b444-b02f0de7586a). No tooltips were being shown when buttons are hovered upon. I was using chrome btw

**Comment by zcolah** [comment]
Thank you for bringing this to my attention. Will add the ticket into the
main bug list for content now.

**Comment by zcolah** [comment]
Issue is now made @Sammieboy00 
https://github.com/zesty-io/manager-ui/issues/2545

**Comment by Sammieboy00** [comment]
Looks good. Thanks!
