### ISSUE TITLE
Content: Confirm Publish Modal - Publish Button does not always get focussed 

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2553]
**Describe the bug**
See Loom: https://www.loom.com/share/8d2c2a7706a245f9befe7b49482ee81a

**Comment by glespinosa** [comment]
@zcolah 

Issue: The button is actually being `focused`, so the main bug/problem is the `ripple` is not taking effect unless we do the keyboard interactions (It is mentioned here ( https://github.com/mui/material-ui/issues/8438#issuecomment-332853834))

Here's a PR that will resolved that issue https://github.com/zesty-io/manager-ui/pull/2573

**Comment by zcolah** [comment]
Thank you for this insight @glespinosa. Would we have to do this for each dialog modal individually? Could we do this the improvement at a theme level? or Would we have to do them separately each time?

**Comment by glespinosa** [comment]
@zcolah I don't find a way yet if that's possible in a theme level.
Unfortunately we need to add this code to every modal with a button that needs to be focus with ripple effect.
