### ISSUE TITLE
Content item header shows Scheduled even if Publish now was clicked

### ISSUE THREAD

**Issue by theofficialnar** [zesty-io/manager-ui#2554]
**Describe the bug**
Content item header shows Scheduled even if Publish now was clicked

**To Reproduce**
1. Go to any content item
2. Make any change
3. Click save then publish

**Expected behavior**
It should not show Scheduled if the user has clicked Publish now

**Screenshots**
[publish-status.webm](https://github.com/zesty-io/manager-ui/assets/28705606/7706cc7b-1062-4466-8a1e-8f57a4d834f9)

**Comment by zcolah** [comment]
@theofficialnar can you please share the instance link to the content item this was happening on?

**Comment by zcolah** [comment]
Seems like it is this one: 
https://8-f48cf3a682-7fthvk.manager.zesty.io/content/6-a1a600-k0b6f0/7-a1be38-1b42ht

**Comment by zcolah** [comment]
**Cannot replicate the issue on my computer.**
https://www.loom.com/share/7cd73c8f7dd8481e852ac1cc4a10f002

**Comment by theofficialnar** [comment]
Seems to be an isolated case that only happens on my computer.
