### ISSUE TITLE
 Schema: Able to select child models as it's model parent.

### ISSUE THREAD

**Issue by kharljhon14** [zesty-io/manager-ui#2580]
**Describe the bug**
Was able to select child models as it's model parent.
When setting the model parent to it's own child model it would freeze the website.

**To Reproduce**
1. Select Dataset model parent to `Invoicepage`
2. Select Single page model parent to `Invoices`
3. Click Save

**Expected behavior**
Should not be able to select child models as it's parent model

**Screenshots**
![image](https://github.com/zesty-io/manager-ui/assets/44658751/c32b5e5f-2208-43a3-a997-3cb96e55c1b7)
![image](https://github.com/zesty-io/manager-ui/assets/44658751/d157371c-6ec3-4cb6-9561-44fe2a877937)

**Comment by giseleblair** [comment]
@kharljhon14 please clarify further what the issue is. There is not a clear understanding of what the problem is here.

**Comment by kharljhon14** [comment]
@giseleblair when setting the model parent in relation to each other, it causes the website to freeze. Even after reloading the website, the freeze persists. Let me know if you need further clarification.

https://github.com/zesty-io/manager-ui/assets/44658751/313a9c98-befd-4c1e-bb15-7e919a136cd5

**Comment by zcolah** [comment]
**@glespinosa We have got @giseleblair's permission to move forward with the following solution:** 
In the Model parent dropdown, please hide a model that is child to the parent in the dropdown for selecting a model parent.

**Comment by glespinosa** [comment]
> **[@glespinosa](https://github.com/glespinosa) We have got [@giseleblair](https://github.com/giseleblair)'s permission to move forward with the following solution:** In the Model parent dropdown, please hide a model that is child to the parent in the dropdown for selecting a model parent.

Alright @zosh thanks for letting me know. Will check on this
