### ISSUE TITLE
Media: Insights tab - Resolve Text Wrapping in Card

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2593]
**Is your feature request related to a problem? Please describe.**
Figma: https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=913%3A284168&mode=dev&t=llY27xUnKmMUKvli-1

![CleanShot 2024-03-14 at 01 18 32](https://github.com/zesty-io/manager-ui/assets/22625919/09687843-766b-4fda-b154-9c4cb9c1b120)

**Comment by zcolah** [comment]
@glespinosa Thank you for that insight. Could you look into what is making the text wrap when the card is 200px? See screenshot. 
Note: In Figma, the same text does not wrap in the card when it is 200px. https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=913%3A284168&mode=design&t=WChJaav6FusFYP1D-1

![Image](https://github.com/zesty-io/manager-ui/assets/22625919/6c4d31f8-4893-41fa-a09e-268c200723a0)

**Comment by glespinosa** [comment]
@zcolah upon checking the container where the icon and text have a gap of 4px

https://github.com/zesty-io/manager-ui/assets/44116036/2b12dfd4-7feb-4a68-acf9-d8cd32c59c36

**Comment by zcolah** [comment]
Hi @glespinosa please make the gap to 0px. And make a PR for the same. I will rename the ticket.
