### ISSUE TITLE
Create item issue - empty item displays in dataset/list

### ISSUE THREAD

**Issue by gtllien** [zesty-io/manager-ui#2599]
**Describe the bug**
When a new item is created, there appears an empty item listed in dataset - there's no way to delete it in UI since it's not yet created but it is shown in the dataset/list

Screenshot:
![image](https://github.com/zesty-io/manager-ui/assets/112954373/a25483bf-6e31-49d3-866d-ff2cf1763eca)

stage url:
https://8-84fbb1fd87-qm8d2d.manager.stage.zesty.io/content/6-b0b6b185c3-q92rjf

**To Reproduce**
1. Go to this [content model](https://8-84fbb1fd87-qm8d2d.manager.stage.zesty.io/content/6-b0b6b185c3-q92rjf)
2. Click on 'Create Item'
3. Create a new item, clicking the **Create** button
4. Then see the table listing of the newly created item - there displays another empty item listed and there's no way to delete it since when open it's not yet created/no item details

**Expected behavior**
An empty item/not yet created should not be displayed in dataset/list

**Additional context**
Note: I'm not able to replicate it in my other test instance, only in the given instance.
See also attached video for reference.

https://github.com/zesty-io/manager-ui/assets/112954373/783db706-3adc-435c-b40a-ddde61327a23

**Comment by zcolah** [comment]
Hi Lien
May you provide a Loom video from the start to the end of the problem?

**Comment by gtllien** [comment]
Hi @zcolah i already attached a video for reference. Thanks

**Comment by gtllien** [comment]
@agalin920 Thanks, I can no longer replicate it once I clear my IndexedDB

**Comment by finnar-bin** [comment]
@gtllien is it safe to close this ticket then?

**Comment by gtllien** [comment]
@finnar-bin Yes. To confirm, moving forward when a user encounters the same will just have to advise them to clear IndexedDB right?

**Comment by finnar-bin** [comment]
@gtllien yup. Tried replicating the issue but I can't seem to be able to replicate this.
