### ISSUE TITLE
Content: Duplicate Item Function Fails to Create Copy of the Item

### ISSUE THREAD

**Issue by SamriddhiSimlai26** [zesty-io/manager-ui#2669]
The Duplicate Item function is currently not functioning as expected. While trying to duplicate a content item, there is no response, no error message and the function does not complete ie. there is no duplicate copy of the item created. 
Additionally, this is happening even though the meta description is within the 160 character limit.

For example, check the error recording while trying to duplicate an Article:
https://github.com/zesty-io/manager-ui/assets/16765661/0b8dbab6-55de-40c3-8252-a364fa7e0972

Meta Description screenshot:
<img width="1224" alt="image" src="https://github.com/zesty-io/manager-ui/assets/16765661/2eaefd70-27b4-474c-97fe-c91d67c70840">

Link to example content item: https://8-aaeffee09b-7w6v22.manager.zesty.io/content/6-45a908-qfw88c/7-b4a8f3da91-rd7mvf/meta

**Comment by zcolah** [comment]
Expected behavior: 
If character count of Meta Title or Meta Description, or Navigation Link text with the word "(copy)" appended to it has a character count above their specified character limit, then: 

**Shorten meta description to account for ‘ (copy)’ at the end**

**Comment by gtllien** [comment]
@finnar-bin Please let me know when this will be fixed as this has been reported by the customer. Thanks
