### ISSUE TITLE
Content: Schedule Modal Time Zone Dropdown Height Bug

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2781]
# Bug
The time zone dropdown menu height is lesser than what it should be. 
![image](https://github.com/zesty-io/manager-ui/assets/22625919/280caade-d688-4c9f-a2c8-076f64cd2614)

# Solution
Please resolve the height issue by referring to the Figma file. Please ensure this reflects in the schedule modal for an individual item and on the multi page table. 

## Figma Reference File
https://www.figma.com/design/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?m=dev&node-id=3518-98269&t=Was6b6R8bLkLnWlw-1

**Comment by geodem127** [comment]
**RCA:** The "small" size was explicitly set for this field, while the others were left unset.
**FIX:** Remove the explicit size setting for consistency with the other fields.
**PR:** https://github.com/zesty-io/manager-ui/pull/3105
