### ISSUE TITLE
Success Banner still shows up when saving fails

### ISSUE THREAD

**Issue by Eerkz** [zesty-io/manager-ui#2812]
**Describe the bug**
I have a granural role for a content item where `create` and `update` permissions are set to false to prevent saving of the content item but when save is clicked, the success banner shows up even though the request correctly fails.

**To Reproduce**
1. Create a custom role based off the developer system role. 
2. Attach a granural role to a content item and add it to the custom role. The permissions should be set to:
```
{
    "create": false,
    "read": true,
    "update": false,
    "delete": false,
    "publish": false,
    "grant": false
}
``` 
3. Go the manager-ui and check the content item. Click save and the success banner will show up even though the request fails (checked by by looking at the request in the network tab or refreshing the page to see that the fields content of the item hasn't change)

**Expected behavior**
Success banner should not be shown when save fails. 

**Screenshots**
<img width="1290" alt="success banner still shows" src="https://github.com/user-attachments/assets/d15df859-4c6e-4bba-bb3a-1cc3a40cf421">

**Additional context**
Instance Zuid: 8-c28bb580b8-8xl3n4
Custom Role Zuid: 30-f6b2e9f7e4-s4vnfd
Granural Role Zuid: 32-8c99a18da3-20x3ms

**Comment by Eerkz** [comment]
> We should not show the publish button at all in this case

hi andres. i opened a separate ticket for the publish button: https://github.com/zesty-io/manager-ui/issues/2811

**Comment by finnar-bin** [comment]
Closing in favor of https://github.com/zesty-io/manager-ui/issues/2811
