### ISSUE TITLE
Date-time field value is saved as "Invalid date"

### ISSUE THREAD

**Issue by arzljames** [zesty-io/manager-ui#2814]
**Describe the bug**
When using Safari browser, it saves as "invalid date" on a date-time field. I tested this issue on Chrome and Firefox, and it works fine.

**To Reproduce**

1. Using Safari, Navigate to Schema and create/define a date-time field
2. Go to Content, add date and time
3. See error: Invalid Date

**Expected behavior**
It should successfully save a date-time value.

**Screenshots**
![screenshot_2024-07-15_at_10 33 30_am](https://github.com/user-attachments/assets/f23e27f6-ec7b-4e3f-9794-c5792f3d5db8)

**Comment by finnar-bin** [comment]
I'm assuming this is also related to this sentry issue since the schedule publish modal is also using the same date time field here and the sentry indicates that the user is using safari as well.

https://github.com/zesty-io/manager-ui/issues/2817
