### ISSUE TITLE
Redirects: Need to Refresh Page to See & Search for Newly Added Redirect

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2818]
# Problem
Customer has reported: 

> Every time I create a redirect I need to refresh my page. 
> It is very time consuming when I need to create several redirects. 
> I should not need to refresh my page.

# Solution

The redirect should be added into the table without the user having to refresh their page.

**Comment by giseleblair** [comment]
Please provide steps to recreate, I am not able to reproduce with the context given above

**Comment by zcolah** [comment]
@giseleblair I am also unable to and have followed up via email with them.

**Comment by zcolah** [comment]
This issue has been resolved via this ticket: https://github.com/orgs/zesty-io/projects/150/views/1?pane=issue&itemId=71995464
