### ISSUE TITLE
Content: Error Blurb Does Not Display All Errors for Invalid Field Values

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2826]
# Problem
1. Assume I start to create a content item. My input text I put into the Title input does not meet the rules and I have forgotten to add in values for required fields. See screenshot below.

![Image](https://github.com/user-attachments/assets/0a1d042d-5078-4fe6-9fbb-71605ba852e5)

2. I click on Create. 
3. I only see the errors for the rules not being met. There are no errors saying that I am missing values for required fields. See screenshot below.
![Image](https://github.com/user-attachments/assets/7b6ac9a5-acb8-4cbe-ae84-746232a199c6)

# Solution
1. The error blurb must display all the errors that are on the page. 
2. The page must also highlight all the fields with errors (such as those with missing required values and those exceeding character count ranges)

**Comment by finnar-bin** [comment]
Related to #2820
