### ISSUE TITLE
Content: HTML source code (WYSIWYG field) issue with name attribute value

### ISSUE THREAD

**Issue by gtllien** [zesty-io/manager-ui#2842]
**Describe the bug**
In the HTML source code, adding a **name attribute with value = `title`** (in input field) appears to be removed upon save

**To Reproduce**
1. Go to a specific content item with WYSIWYG field
2. In WYSIWYG field click the '**HTML**' icon
3. Edit/add a name attribute with value = `title` in input field
4. Click SAVE then see the **name attribute value = `title`** disappears

**See video test**

https://github.com/user-attachments/assets/371a81fe-975a-4d6a-8094-50be618a0d34

**Expected behavior**
In the HTML source code of a WYSIWYG field, adding a name attribute with value = `title` (in input field) should be accepted and value should remained when saved

**Additional context**
Reported in [Zoho Ticket #2586](https://general.support.zesty.io/agent/zestyio/zesty-io-support/tickets/details/603828000011079001)

**Comment by finnar-bin** [comment]
Note: only removes the name attribute if the value is exactly **title** (case sensitive)

**Comment by finnar-bin** [comment]
@gtllien based on my research regarding this issue, it turns out that this is by design and not a bug in TinyMCE itself. They're using DOMPurify to sanitise HTML and prevent XSS. DOMPurify has a rule for `id` and `name` attributes that auto-strip values that exists in the DOM. 

Reference: https://github.com/tinymce/tinymce/issues/9613#issuecomment-2091169166

**Comment by gtllien** [comment]
Thanks for checking @finnar-bin 
In this case, there's no other way but to use other values in id/name that don't exist in DOM?

**Comment by finnar-bin** [comment]
@gtllien yup, exactly.

**Comment by gtllien** [comment]
Thanks @finnar-bin closing the ticket
