### ISSUE TITLE
Internal/External link does not work

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#292]
**Describe the bug**
In the content section you can select to create an Internal/External link item but the dropdowns do not work so a link cannot be created. 

**To Reproduce**
1. In the content section click the Create Item dropdown and select Internal/External link
2. Fill out the form for creating an Internal/External link item and see that the dropdowns do not have any options for selecting items.

**Expected behavior**
I expect to be able to select parent items and Links To items from the dropdowns.

**Screenshots**

<img width="1434" alt="Screen Shot 2020-10-19 at 4 10 36 PM" src="https://user-images.githubusercontent.com/16694502/96523131-c8fe4c00-1229-11eb-955d-3735ed38aa71.png">

<img width="835" alt="Screen Shot 2020-10-19 at 4 11 13 PM" src="https://user-images.githubusercontent.com/16694502/96523141-d0255a00-1229-11eb-8ffb-7436df218183.png">

<img width="837" alt="Screen Shot 2020-10-19 at 4 11 44 PM" src="https://user-images.githubusercontent.com/16694502/96523149-d4ea0e00-1229-11eb-8786-b6584ad14291.png">

**Desktop (please complete the following information):**
 - OS: Mac 10.15.7
 - Browser Chrome
 - Version 86.0.4240.80 (Official Build) (x86_64)

**Additional context**
While this is not commonly used by the majority of our customers - we have one non-technical customer uses this often.
<br><br><i>(related to <a href='https://zestysupport.zendesk.com/agent/tickets/1233'>Zendesk ticket #1233</a>)<br>gz#1233</i>

**Comment by shrunyan** [comment]
Will need to account for this related issue. https://github.com/zesty-io/manager-ui/issues/438

**Comment by shrunyan** [comment]
@nibblebot selecting external link and putting a value into the external link input and then switching to internal links causes it's dropdown selected to disappear. I imagine this is because the external link value is used to match the list on internal link and there is none, breaking it.
