### ISSUE TITLE
Content: Comments - Improved Email Notifications

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2920]
# Intro
We are making the following improvements to email notifications: 

## Open Comment Button
![Image](https://github.com/user-attachments/assets/0b6663e2-43e2-4567-9f32-05b0acd9414d)

## Better Contrast in Dark Mode
![Image](https://github.com/user-attachments/assets/73bb1073-4950-4ea3-abed-25cc8fc95fe5)

# Figma
https://www.figma.com/design/6TyAXXvHmF3zunsmUn8Ji1/Comments?node-id=462-63031&m=dev

# Logo File

![Image](https://github.com/user-attachments/assets/bf4f9a97-d751-44d8-a91a-f04d7ed33f81)

**Comment by zcolah** [comment]
@markelmad would you be the person responsible for this project?

**Comment by markelmad** [comment]
@zcolah there will be a slight changes to the body of the email. but the overall appearance will be for @allenpigar . I'll coordinate with him regarding this.

**Comment by allenpigar** [comment]
@zcolah ill be moving this ticket to gcp-cf repo. i already have pr for this ticket and already merged. https://github.com/zesty-io/gcp-cf/pull/173

**Comment by zcolah** [comment]
Please let me know how I can do the VQA for it

**Comment by allenpigar** [comment]
@zcolah i believe this is already deployed on all env. i believe you can test this by using the commenting system, im i right @markelmad ?

**Comment by markelmad** [comment]
@allenpigar @zcolah This still needs some some changes on the accounts-api repo. I'll be focusing on this this week and will let you know once it is on stage for testing.
