### ISSUE TITLE
Incorrect display of relational field

### ISSUE THREAD

**Issue by gtllien** [zesty-io/manager-ui#2963]
**Describe the bug**
Use-case from customer:
We are seeing wrong field value on one-one relational field in model list view.
For HomeBase instance, for 'Services by Price' model we have 1-1 relation of services where we select service based on title as follows.
When we see in list view it should show  **Service Title** in column and not ID , even if IDs being shown those should not be from meta fields. 
 
Please see below screenshots:
 
Value of ID from meta title in 1-1 relational model(this should be title):
![image (15)](https://github.com/user-attachments/assets/865a13f8-332e-4011-8ded-1c7ef4d63d32)

What we have selected as relation field ( **Service Title**):
![image (16)](https://github.com/user-attachments/assets/73207355-2f01-45ef-a37a-1148e8b13d51)

What is actual Id ( our custom field : id) and meta title (this value appears to be displayed in list instead of the **Service Title**)
![image (17)](https://github.com/user-attachments/assets/a7e3841a-e034-43d7-a5c9-1e8ea05b5f71)

![image (18)](https://github.com/user-attachments/assets/ad0ce911-fedd-4232-97c2-5e856a8ad67f)

**Expected behavior**
Relational field value selected should be displayed correctly

**Comment by finnar-bin** [comment]
Fix should already be live in prod @gtllien
