### ISSUE TITLE
Schema: Deactivate Field Bug

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2966]
**Describe the bug**
Please watch loom video: https://www.loom.com/share/ca4630fbadbc4f9ba4161810aeb70924

**Solution**
Ideally the field should only be de-activate once the user clicks on the Save button in the modal. Until then the de-activated state should not be finalized. 

If the above solution cannot be achieved then immediately close the modal once the user clicks on de-activate field.

**Comment by finnar-bin** [comment]
@zcolah what should the deactivate/reactivate button look like after clicking it and the user hasn't clicked the save button yet? I think a clear indication that they have marked that item for deactivation/reactivation once saved is clicked is needed to prevent accidental actions.
