### ISSUE TITLE
Blocks App: Phase 1 - Base App

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2997]
This ticket is a WIP

# Intro
Freestyle users will now be able to create Blocks in the Zesty platform for different types of sections on their website such as Hero, Feature, Testimonials, etc. These blocks can then be leveraged and used to build web pages in Freestyle. 

The setup process looks like this: 

1. The user creates a Block Model in the Schema App
2. The user adds code to the supporting code template file in the Code App
3. The user creates, saves, and publishes a variant of block in the Blocks App
4. The user drags and drops this variant of the Block into a web page in the Freestyle App

# User Flows to Build

### All Models Page 
- [x] Creates a Block Model

### View Model Page
- [x] Adds fields to the Block Model
- [x] Info Tab

## Code App
- [x] Edits, Saves, and Publishes code template file in the Code App

### All Blocks Page

User: 

- [x] Views All Blocks
- [x] Creates Block (shortcut)
- [x] Searches All Blocks via Sidebar
- [x] Searches All Blocks via the All Blocks Section (Success)
- [x] Searches All Blocks via the All Blocks Section (Failure)
- [x] Adds Block Group
- [x] Delete Block Group
- [x] Adds Block to Block Group
- [x] Changes Group a Block Belongs to

### Create Variant Page
- [ ] Creates Variant

### View Block Variants Page

- [ ] Views Variant
- [ ] Edits, Saves, and Publishes a Variant
- [ ] Opens More Menu: 
  - [ ] Copy ZUID
  - [ ] Edit Code Template
  - [ ] Edit Model
  - [ ] Duplicate Variant
  - [ ] Delete Variant
  - [ ] Views API endpoints
- [ ] Searches Component Variants (Success)
- [ ] Searches Component Variants (Failure)
- [ ] Sorts Component Variants
- [ ] Switches to Another Variant
- [ ] Creates Variant
- [ ] Switches to Info Tab

# Developer Notes
## Instances API Updates
- [x] https://github.com/zesty-io/instances-api/issues/611
## Web Engine Updates
- [ ] https://github.com/zesty-io/webengine/issues/432

## Permission
All users with access to the Content App, should be able to see the Blocks App. 

# Figma
https://www.figma.com/design/oiesa7e6Q5mcGEAyOjYCtJ/Blocks-App?node-id=132-1587&m=dev&t=7je4uuIZAJBCjEAh-1

**Comment by zcolah** [comment]
Have provided the revised list below which contains replies to all questions asked in the comments below.

**Comment by agalin920** [comment]
@zcolah please provide written replication steps for

Screenshot in Preview is not the same as the Screenshot in the Table.

**Comment by agalin920** [comment]
@zcolah regarding the sidepanel changing sizes

This is the figma definition
Preview and Variants Container:
Minimum width: 360px
Unbounded Maximum

By this definition certain things that will want to take up more space will render a larger space where as smaller items like the variants will only take up the minimum width. Your designs are set at a width of 542px. Do you wish that to be the minimum instead?

**Comment by agalin920** [comment]
@zcolah Updated By Value is missing in the variants table

Written Replication steps please. Does the user have a first or last name?

**Comment by agalin920** [comment]
Screenshot system is not taking a screenshot of the entire block and is adding unnecessary white space to blocks in some cases

@allenpigar  can you take a look at this request and respond to @zcolah

**Comment by allenpigar** [comment]
@agalin920 are you using the same url as in preview when taking the screenshot?

**Comment by agalin920** [comment]
> @agalin920 are you using the same url as in preview when taking the screenshot?

Yes

**Comment by allenpigar** [comment]
@zcolah the createScreenshot only takes screenshot the page upon rendering to a browser. currently there is no feature on the screenshot to take a specific area of the page.

**Comment by agalin920** [comment]
@zcolah pleas specify here what solution we want for the preview in create experience and where it is on priority

**Comment by zcolah** [comment]
# Bugs

## High Priority

- [x] The Preview is missing from the Create Experience. Update: We have decided to update the Create Experience to be the following: https://www.figma.com/design/oiesa7e6Q5mcGEAyOjYCtJ/Blocks-App?node-id=672-31769&t=1B6ZRnd0LT193rum-1. Please make the required design changes. 

![CleanShot 2024-12-11 at 21 25 09](https://github.com/user-attachments/assets/c503224a-a970-4a65-9c3d-019eb387ff9d)


## Medium Priority

- [x] The right panel width changes when the user switches to the Info Tab. This should not happen. It should follow the same  rules of changing width as the Variants Tab. Discussed on call with you. See Loom: https://www.loom.com/share/80b064be2c464f4b84132fefcc3e7844

- [x] No Search Results changes the width of the right panel. This should not happen. | [See Figma](https://www.figma.com/design/oiesa7e6Q5mcGEAyOjYCtJ/Blocks-App?node-id=669-34068&t=mkcy2mrKsJSFfTri-1) : https://www.loom.com/share/6f7c72f0871a489cb16127c2ded2ef1e

- [x] Updated By Value is missing in the variants table. This should not happen. Replications steps are to first create a variant, then save a v2 of the variant. Yes the user has a first and last name (aka Zoshua Colah). My name appears in other spots of Zesty. Just not here. See Loom: https://www.loom.com/share/7de812e5cee6493799e41684e1b33f80

## Low Priority

- [x] Cancel button should not appear in the Preview Panel | [See Figma](https://www.figma.com/design/oiesa7e6Q5mcGEAyOjYCtJ/Blocks-App?node-id=160-35964&t=iAC0VXmIAD2wng3M-1) : https://www.loom.com/share/78c4cab93aea4873ab651f358aa73826

- [x] Preview URL should not display in the Preview Panel | [See Figma](https://www.figma.com/design/oiesa7e6Q5mcGEAyOjYCtJ/Blocks-App?node-id=160-35964&t=iAC0VXmIAD2wng3M-1)

- [x] Delete Item button in the Info Tab should say Delete Variant | [See Figma](https://www.figma.com/design/oiesa7e6Q5mcGEAyOjYCtJ/Blocks-App?node-id=185-42942&t=iAC0VXmIAD2wng3M-1) : https://www.loom.com/share/8a83abda52af4cc496d7e8ded49c945c

- [x] Check that the info tab has only the relevant sections and that it has replaced the word content item with variant all over. [See Figma](https://www.figma.com/design/oiesa7e6Q5mcGEAyOjYCtJ/Blocks-App?node-id=185-42942&t=HOgpdu5YMJxwYPSa-1)

- [x] Publish Modal should say Publish Variant not Publish Content Item | [See Figma](https://www.figma.com/design/oiesa7e6Q5mcGEAyOjYCtJ/Blocks-App?node-id=160-37465&m=dev&t=iAC0VXmIAD2wng3M-1) : https://www.loom.com/share/c166515866e444bbb839a116a6055ccf
- [ ] Screenshot system is not taking a screenshot of the entire block and is adding unnecessary white space to blocks in some cases. @allenpigar It does not seem to be screen shoting the entire page. See Loom: https://www.loom.com/share/f40c33fbd2644fd78746617c386ae605

# Enhancements

- [x] Variant Table: Screenshot should be object-fit: contain. See Loom: https://www.loom.com/share/de04c1e1cb8f43198f1a4b548e053e04

# Figma VQA 

- [x] Complete VQA tasks listed here: https://www.figma.com/design/oiesa7e6Q5mcGEAyOjYCtJ/Blocks-App?node-id=665-33564&t=HOgpdu5YMJxwYPSa-1

# Problems that Need a Resolution from Up Top (Stuart and Randy)

- [ ] Screenshot in Preview is not the same as the Screenshot in the Table. This should not happen. They should be the same. See Loom describing the issue: https://www.loom.com/share/b04ab53e09c649b694037819166ea060?from_recorder=1&focus_title=1

Below is a screenshot highlighting the issue better. 
 
**Update 1:** 
- We discovered that this happens because the CSS of the code file was updated. 
- Our system does not retroactively update the screenshots of all the variants created when the CSS or HTML files in the Zesty are updated. More so we will never know if the CSS of an external system is updated.  
- This means that the variant screenshots may not always be an accurate representation of the current design of the Block (unless the user goes and creates and saves a new version of each Block).  

There is no fast solution to this. @agalin920 has recommended we use iFrames. 

**Update 2:** 
Randy has shared that we do not prioritize resolving this issue for v1. We can work on it later. 

![CleanShot 2024-12-11 at 21 23 29](https://github.com/user-attachments/assets/bc003c93-0529-4b07-a41a-287868fe2a7e)

**Comment by agalin920** [comment]
@zcolah Regarding "Updated By Value is missing in the variants table"

I just verified that you do not have a user in that instance. Remember accessing an instance as staff does NOT guarantee you have a user associated to that specific instance. We require a user to be associated to the instance for the name to come up
