### ISSUE TITLE
Content: Datetime field cannot select time in PM

### ISSUE THREAD

**Issue by gtllien** [zesty-io/manager-ui#3031]
**Describe the bug**
When a user selects time in **PM** in the dropdown selection of a datetime field, it reverts to AM 

**To Reproduce**
1. Go to content item with datetime field
2. Select a date and a time in PM (eg. 11:00 pm)
3. See how it reverts to AM instead of the selected time in PM

**Expected behavior**
User should be able to select a datetime not only in AM but in PM as well

**See video capture for reference**
![chrome_C2yaGRCm5l](https://github.com/user-attachments/assets/3af5f33a-314b-4cf8-bc2f-c0ae5d10086a)

**Comment by agalin920** [comment]
closed by #https://github.com/zesty-io/manager-ui/pull/3030
