### ISSUE TITLE
Schema -> content model creation toggles & dropdown inconsistent

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#306]
**Describe the bug**
When creating a content model, there are toggles that help a user select their content model type. When those toggles are flipped the "selected model type" dropdown is automatically changed based on the toggles. However, if a user selects a model from the dropdown, the toggles remain unchanged. This can be confusing for the user. 

**To Reproduce**
1. Navigate to Schema
2. Click on the _Model Type_ toggles and see the _selected model type_ dropdown change
3. Use the _selected model type_ dropdown to change the content model type and see that the _model type_ toggles do not change.

**Expected behavior**
If the dropdown should automatically change the toggle selection. OR if the purpose of the toggles is an OR situation - meaning - use the toggles to select the content model type OR use the dropdown that needs to be clear in the UI. 

**Screenshots**

<img width="341" alt="Screen Shot 2020-10-21 at 11 32 38 AM" src="https://user-images.githubusercontent.com/16694502/96768290-90c64d00-1392-11eb-9b06-d268e5bb7c8a.png">

**Desktop (please complete the following information):**
 - OS: Mac 10.15.7
 - Browser Chrome
 - Version 86.0.4240.80 (Official Build) (x86_64)

**Comment by shrunyan** [comment]
I am up for re-working this experience. The _intent_ this wizard is trying to implement is helping users understand the difference between schema models with URLs and those without. As that was a common point of confusion previously. e.g. _User creates a headless model then later decides they want URLs and then realize that model does not support them_

This UI attempted that in two ways;

1. Body copy attempting to explain the nuances of the various models
2. A wizard to present outcome questions, selecting the appropriate model based on the answers.

Both are beneficial, meaning it's important we can help users understand the different models by explaining it but for an experience perspective I think the wizard presenting questions in terms of outcomes aligns closer to the users intent at the time of creation.

Whatever experience is proposed it's important it keeps that in mind. Success would be users fully understand what a model type does and does not do allowing them to select the appropriate model for their use case.
