### ISSUE TITLE
Internal/External Link Title fields do not accept apostrophe

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#309]
**Describe the bug**
when creating an Internal/External link item in the Content section, if there is an apostrophe in your Link Title field, it causes a 500 on creation. However, the item will still be completed, but all fields will be blank. If you try to change the Link Title name after it's been created to add an apostrophe in the Link Title field & save you'll get a success notification even though it doesn't save the apostrophe.

**To Reproduce**
1. Navigate to the Content Section
2. Click on the Create New Item dropdown at the top of the left-hand nav bar & select Internal/External Link
3. Select either internal or external from the first field in the dropdown, and fill out the fields and when you get to Link Title enter a word with an apostrophe and click **Create New Link** button. See 500 error. 
4. Remove apostrophe from title and click **Create New Link** button. 
5. With the newly created link's Link Title field, add an apostrophe and click **Save Changes** and see success notification.
6. Give the browser a refresh and see that the apostrophe that you added in step 5 was not actually saved.

**Expected behavior**
Aspostrophes should be a valid character type in the Link Title field. Internal/External links are creatable and savable whether or not there is an apostrophe in the Link Title or not.

**Screenshots**
<img width="1209" alt="Screen Shot 2020-10-21 at 3 02 30 PM" src="https://user-images.githubusercontent.com/16694502/96793011-608da700-13b0-11eb-935d-2b9edff15068.png">

**Desktop (please complete the following information):**
 - OS: Mac 10.15.7
 - Browser Chrome
 - Version 86.0.4240.80 (Official Build) (x86_64)

Related Zendesk ticket #943

**Comment by shrunyan** [comment]
fixed https://github.com/zesty-io/manager-ui/pull/646
