### ISSUE TITLE
Global > Validation Helper Limits match hard to see  

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#335]
**Is your feature request related to a problem? Please describe.**
Validation Helper Limits

**Describe the solution you'd like**
Make color match font 
color: #5b667d;

<img width="194" alt="Screen Shot 2020-10-29 at 2 01 32 PM" src="https://user-images.githubusercontent.com/22800749/97632093-41fe6000-19ef-11eb-8021-f7f510c82113.png">

**Comment by shrunyan** [comment]
Resolved https://github.com/zesty-io/design-system/pull/77
