### ISSUE TITLE
Notification Styles Feature

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#349]
**Is your feature request related to a problem? Please describe.**
add icons that will correspond to the notification message

**Describe the solution you'd like**
Design considering the importance of your message

**Describe alternatives you've considered**
Leave as is

**Additional context**
https://uxdesign.cc/a-comprehensive-guide-to-notification-design-2fff67f08b7a#:~:text=The%20placement%20of%20notifications%20is,of%20notifications%20with%20various%20viewports.

https://uxplanet.org/how-to-design-notifications-for-better-ux-6fb0711be54d

https://ux.stackexchange.com/questions/39265/placement-of-flash-growl-notifications-or-messages-in-web-application

Current
![Screen Shot 2020-10-30 at 11 33 36 AM](https://user-images.githubusercontent.com/22800749/97744590-be9f4600-1aa4-11eb-9bb1-6d89eee47327.png)

Possible styles: 
![Screen Shot 2020-10-30 at 11 35 42 AM](https://user-images.githubusercontent.com/22800749/97744191-0d001500-1aa4-11eb-92a3-eb9418a83212.png)

**Comment by shrunyan** [comment]
related https://github.com/zesty-io/manager-ui/issues/544
