### ISSUE TITLE
Content > Meta view labels  

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#361]
**Is your feature request related to a problem? Please describe.**
Labels are not equally alined and sized properly

**Describe the solution you'd like**
the labels are duplicated in many pages and could use a global style possibly in shell

**Describe alternatives you've considered**
look into design-system to have a typography helper.

<img width="693" alt="Screen Shot 2020-11-03 at 10 59 41 AM" src="https://user-images.githubusercontent.com/22800749/98031207-0553af80-1dc7-11eb-9733-5b9add2c64ba.png">

**Comment by shrunyan** [comment]
@d88naimi was this solved?

**Comment by d88naimi** [comment]
@shrunyan Yes I swapped out the label to utilize design-systems FieldLabel component. Not needing to alter design-systems.
EX:https://github.com/zesty-io/manager-ui/commit/d85a12e9684fbe1f6269c600a9acc65e569c8133 

This can be closed.
