### ISSUE TITLE
Publishing Table on Individual Content View

### ISSUE THREAD

**Issue by ardeay** [zesty-io/manager-ui#37]
**Is your feature request related to a problem? Please describe.**
Customers need to see the history and current and future of what versions have been and will be published

**Describe the solution you'd like**
A tab on the content page next to meta that shows a table of chronological publish records

**Comment by d88naimi** [comment]
@stuart Will the release app include this "history records" view?

**Comment by shrunyan** [comment]
@d88naimi it will not. It will only include an interface from which to manage what content is part of a release.

**Comment by d88naimi** [comment]
@ardeay The Content Dashboard now shows the history of Edits and Publishes of the current user. Are we looking to add a section that includes all users that have made changes? 

Will this be a feature to future Audit Trail or should this enhancement be in Dashboard?  

![Screen Shot 2022-01-03 at 1 30 17 PM](https://user-images.githubusercontent.com/22800749/147982449-efd43eaa-2893-421a-88e5-ed22d7ab28db.png)

CC: @shrunyan

**Comment by shrunyan** [comment]
this has been built
