### ISSUE TITLE
Color Picker that allows for pasteable values

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#373]
**Is your feature request related to a problem? Please describe.**
It's frustrating that users cannot paste hex values into the colorpicker field type. It's also very difficult to diagnose any issues since colorpickers are dictated by browser/os. For example users on Windows & Chrome see a different colorpicker than I see on Mac & Chrome.

**Describe the solution you'd like**
I want the colorpicker to: 
1. allow values to be pasted in
2. the same application across all browsers (instead of using browser/os default)

**Describe alternatives you've considered**
users currently type in their Hex values instead of pasting them in and it's cumbersome for them.

**Comment by d88naimi** [comment]
Not sure if this a huge enhancement or blocker for users at the moment so I am closing this one out for now.
CC @shrunyan
