### ISSUE TITLE
Graphical Workflows

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/manager-ui#380]
_Feedback comes from a prospect during a series of discovery calls for an enterprise hybrid CMS._

**Is your feature request related to a problem? Please describe.**
In Zesty.io, workflows could be more robust. There is no central dashboard for workflows, nor are there instructions for managing or executing workflows. 

**Describe the solution you'd like**
Graphical (meaning a visual UI associated with this feature) workflows is 2 pronged: 

1. **Dashboard.** It's requested that there be a central place to see outstanding workflows, completed items, feedback, where you (user) can see what you need to do/by when.
2. **Instructions manager.** It's requested that there be a central place to create instructions for workflows, and that on the right hand side in the UI, users are able to see where a content item is in workflow. (I.e. a workflow for a blog article will be vastly different from changing Terms and Conditions - being able to manage those instructions separately would be necessary.)

**Describe alternatives you've considered**

- Integrations with existing PM services, like Asana, Trello, Wrike, etc.  

**Additional context**
N/A

**Comment by d88naimi** [comment]
Moving this ticket to https://github.com/zesty-io/react-app-loader 
New issue here https://github.com/zesty-io/react-app-loader/issues/1
