### ISSUE TITLE
WYSIWYG drop down functionality is broken

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#384]
**Describe the bug**
When selecting a WYSIWYG dropdown the editor  fails

**To Reproduce**
1. Go to http://8-f48cf3a682-7fthvk.manager.dev.zesty.io:8080/content/6-556370-8sh47g/7-b939a4-457q19
2. Click on any of the dropdowns 
4. See error "Invalid Editor"

**Expected behavior**
WYSIWYG editor view should render

**Screenshots**
<img width="1125" alt="Screen Shot 2020-11-09 at 2 21 04 PM" src="https://user-images.githubusercontent.com/22800749/98603793-8b746800-2297-11eb-846c-d151a794ecf6.png">

**Comment by kakoga** [comment]
this is old behavior that used to work - for a time users were allowed to switch between specific field types: wysi, article writer, markdown, html - this was used to make it easier for users to input the type of content that they wanted. I think that this is still important functionality that we may want to revisit... though I honestly don't know how often Article Writer is used anymore...

**Comment by shrunyan** [comment]
Fixed https://github.com/zesty-io/design-system/pull/57/commits/8d89fa514a29c7fbace92fc789137551715c6784#diff-6f8d3b4f6e324e34e668f78ff3e905dc4e25a2d2375e03c3d0031ee997ea49c3L68
