### ISSUE TITLE
Code: CSS with file path not shown with compiled styles

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#388]
**Describe the bug**
Style sheets which are "compiled", see https://zesty.org/services/web-engine/css-processing-flow, are shown next to each other to indicate as such. Previously the API did not allow for paths to files as all files were created in Zesty dynamically and so paths were not needed. With the introduction of "custom" files we added the ability to enter a path to a file. Which when done so will show that as a tree structure in the code nav.

When creating a CSS file with a path it interpret it as a custom file and shows the resulting tree structure along with the other custom files and templates. Although in reality it is a CSS file that is complied into the combined `site.css` file.

**To Reproduce**
1. Go to /code
2. Click on "Create File"
3. Select "CSS File"
4. Enter path to file; `/path/to/file.css`
5. See tree structure not being displayed next to other compiled css

**Expected behavior**
The logic which builds the nav tree structure needs to separate out all css, less and sass file types which are not custom and display them together. Even if they have a file path. Which should be displayed as a tree structure but along side  the other compiled style sheets. 

**Screenshots**
https://files.slack.com/files-pri/T1RRP29GS-F01EJTJF9A9/image.png

**Comment by d88naimi** [comment]
Notes* https://www.screencast.com/t/XJ6N02Bka

**Comment by d88naimi** [comment]
@shrunyan I want to confirm when following your reproduce instructions, your expectations are to have the file.css inside of SITE.css section see screen shot https://www.screencast.com/t/zyMNvKLV01D
