### ISSUE TITLE
Media: in-app image editor

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#404]
**Is your feature request related to a problem? Please describe.**
not all users have the skills/software to do simple manipulations to images. It would be great if Zesty had a simple photo editor built in. 
It's also cumbersome to upload a photo, realize that something about it doesn't work because, say, it needs a little cropping - and then the user has to delete the photo, rename it, crop it, and re-upload it. 

**Describe the solution you'd like**
I would love a simple built-in photo manipulation software with simple features like cropping, rotating, straightening, and adding text. 

**Describe alternatives you've considered**
I've always used whatever was available to me online, on my computer, and renamed, deleted, re-uploaded photos until I've got it right - it's not a great user experience.

**Additional context**

**Comment by kakoga** [comment]
cc @chloespilotro since I've heard you mention this too and you might be able to add more detail

**Comment by shrunyan** [comment]
Could we add pre-configured our minimal inputs that allow generation of OTF image urls. Which are then shown within the image preview workspace. This way the image manipulation effects could be seen beforehand and the associated url generated to be copied. 

![media-modal-filename-layout (1)](https://user-images.githubusercontent.com/208819/156451919-184bfe1e-1876-475f-a67f-453a903c129b.png)
