### ISSUE TITLE
URL paths are showing as invalid

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#409]
**Describe the bug**
previously created page/multi-page item's URLs are showing as invalid (red X) when they _are_ valid.  They will often show a green check for a second, then show the red X. If you change an existing path by adding something like a dash or extra letters they will then show green-checkmark valid. 

**To Reproduce**
1. In the Content section click on a page or an item in a multi-page set
2. Click on the Meta tab to see the that item's path
3. See the red X next to the path

**Expected behavior**
I expect valid paths to show the green check mark and invalid paths to show a red X.

**Screenshots**
<img width="1423" alt="Screen Shot 2020-11-19 at 12 05 43 PM" src="https://user-images.githubusercontent.com/16694502/99718905-75696300-2a60-11eb-904d-b7383a90b92a.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 86.0.4240.193 (Official Build) (x86_64)

**Comment by shrunyan** [comment]
fixed https://github.com/zesty-io/manager-ui/commit/5e073a9a162fa5f07a4162a9c711a09e7348fa4c
