### ISSUE TITLE
IDE always starts user at top of file once navigating away & back to tab

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#413]
**Describe the bug**
When working in a large IDE file I can be scrolled half way through it, and may need to navigate away to another open item (tab) in Manager UI to reference something, and when I click back into the IDE file I am scrolled to the top of the file and need to find the place where I left off again. 

**To Reproduce**
1. Open a content item
2. Go to the IDE and open a large code file - one that will require scrolling to see all of your code. Scroll down to a mid-point or so
3. Click the tab for the content item you opened in step 1
4. Click back into IDE file tab that you opened in step 2 and see that the file is now scrolled to the top again.

**Expected behavior**
I expect the IDE file to be scrolled to the same line where I left off when I navigate away and back to it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 10.15.7
 - Browser Chrome
 - Version 87.0.4280.67

**Additional context**
I don't know if this belongs here - could be an enhancement - filing here because my expectation is to not lose my place when navigating away from an IDE file and back again.

**Comment by shrunyan** [comment]
Interesting. Possible we could capture the line number from the monaco editor before url change and then reload to that line number when returning.

**Comment by shrunyan** [comment]
Duplicate https://github.com/zesty-io/manager-ui/issues/927

**Comment by d88naimi** [comment]
Duplicate : https://github.com/zesty-io/manager-ui/issues/928
