### ISSUE TITLE
unable to scroll to see all media

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#437]
**Describe the bug**
just like the other scroll bug: https://github.com/zesty-io/manager-ui/issues/422 I am unable to access the image's settings in the last row of images.

**To Reproduce**
1. Go to an instance that has a lot of images
2. media
3. scroll down - see that you can't see the settings cog on the last row of images. 

**Expected behavior**
I expect to scroll down to be able to access my images' settings. 

**Screenshots**
<img width="1439" alt="Screen Shot 2020-12-14 at 4 22 10 PM" src="https://user-images.githubusercontent.com/16694502/102152155-49f05300-3e29-11eb-8cc4-4fc4bf4b1233.png">

**Desktop (please complete the following information):**
- OS: Mac 13" screen
- Browser Chrome
- Version 87

**Comment by shrunyan** [comment]
@d88naimi along with solving this in the current code please ensure we do not have a regression with the ongoing media rebuild.
