### ISSUE TITLE
Scheduling item to publish will immediately publish item

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#444]
**Describe the bug**
When an item is scheduled to publish at a date in the future, that item is instead published immediately. 

**To Reproduce**
1. Go to a content item
2. Click on schedule icon and select a future date to publish the item.
3. When the item is scheduled, note the confirmation message saying the item has been scheduled to publish.
4. Exit the schedule module and see the item has instead been published.

**Expected behavior**
When an item is scheduled to publish, the expected behavior is that the item/version will not go live until the selected schedule date.

**Loom**
https://www.loom.com/share/ef022123c7b8453aa6f7062bb024c830

**Comment by snvboy** [comment]
For me, the scheduling feature is working correctly when using the legacy UI. My guess is this would indicate a bug in the new UI layer, not with the scheduling of publishing itself.

**Comment by shrunyan** [comment]
Resolved https://github.com/zesty-io/manager-ui/pull/445
