### ISSUE TITLE
Settings: instance general savings not saving

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#446]
**Describe the bug**
Instance settings seem to hang on saving and even though there is a 200 in the network tab on refresh the setting doesn't seem to have persisted and Legacy does not show that the setting has been changed. 

**To Reproduce**
1. In Manager UI go to the Settings section and look at the General Settings NOTE: All instances are not affected by this it - ok to test on zuid: 8-def6fa81b8-lh0rxg
2. Flip the toggle on one of the settings like Force WWW and click Save
3. Notice the save button turns gray and the setting doesn't save. 
4. Check Legacy - you'll see the setting hasn't persisted. 

**Expected behavior**
Any changes to settings will properly save and the same state (force HTTP Y/N, force www Y/N, etc.) will show across Manager UI and Legacy

**Screenshots**
<img width="864" alt="Screen Shot 2020-12-18 at 4 31 15 PM" src="https://user-images.githubusercontent.com/16694502/102675698-30b01500-414f-11eb-9cc1-480740e6ce55.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 87

**Additional context**

**Comment by shrunyan** [comment]
@nibblebot this whole area needs an overhaul. There are fundamental issues with it. When you have time for this bug would you evaluate a quick solution, solving the immediate issue, and long term refactor to get the settings more stable.

**Comment by kakoga** [comment]
@shrunyan this is the other bug that needs to be resolved before sunsetting legacy - I still use legacy to modify ssl settings
