### ISSUE TITLE
Revamp Device Emulator in Live Preview

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/manager-ui#461]
**Is your feature request related to a problem? Please describe.**
The devices in the live preview emulator are outdated and misnamed (i.e. iPad portrait is actually landscape). This is a tool that demos extremely well and is asked about in almost every sales cycle at some point. 

**Describe the solution you'd like**
In a perfect world, a browser emulator (if that's possible? i.e. to see how views render in Safari, Chrome, MS Edge, etc.). If not, more/updated devices would demo very well. Based on research of top phones sold in 2020, the ones that make the most sense would be: 
- Samsung Galaxy S20 / S20 Plus (different dimensions)
- iPhone 12 pro max/ iPhone 12 / iPhone 12 mini (all 3 different dimensions)
- Samsung Galaxy Note 20 Ultra
- iPhone SE 2020
- Google Pixel 5
- Samsung Galaxy S10e
- Motorola One 5G
- iPad

Ability to toggle each device to portrait/landscape would be great.

**Describe alternatives you've considered**
N/A 

**Additional context**
N/A

**Comment by d88naimi** [comment]
This is a tough one all the devices are in pure css and this would require quite a bit of time to update to modern devices which are always changing. 

I think a potential solution would be to build a window resizer tool that allows the user to set their desired height and width.

Notes/Inspirations https://bluetree.ai/screenfly/

CC: @shrunyan

**Comment by shrunyan** [comment]
closing in favor or https://github.com/zesty-io/manager-ui/issues/1446
