### ISSUE TITLE
Audit Trail slide up/down for compact view.

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#469]
**Is your feature request related to a problem? Please describe.**
It's difficult to sort through Audit Trail records and it can be confusing too. I think that having different views could work towards resolving this. 

**Describe the solution you'd like**
Instead of having all records listed out what if items grouped by zuid and you could click the item and have it slide down/up to view the records related to that item. I think that might make it easier to view records for a specific item. It would also be nice to have a filter in there for display by most recent or display grouped by item.  

<img width="1380" alt="Screen Shot 2021-01-22 at 2 33 48 PM" src="https://user-images.githubusercontent.com/16694502/105557655-98fb9480-5cc1-11eb-874e-734e9ef31d6c.png">

**Describe alternatives you've considered**
The search function could be used to find an item but I feel like it may be easier to present the records grouped instead or forcing a search. 

**Additional context**
With a solution like this I think that items need to be searchable by zuid or path. I think that it could be useful to have a jump link from content and code items that go straight to audit trail and audit trail will automatically be filtered for that item. I think that this will improve the usability of audit trail

**Comment by kakoga** [comment]
@ardeay  Since you recently mentioned this - here are some ideas I had around the Audit Trail UI and making it more useful for users.

**Comment by shrunyan** [comment]
I imagine there are a few ways logs could be grouped. Not sure how we would visually do so.

1. By resource. e.g. item zuid
2. By user
3. By action. e.g. publish

There purpose to these groupings being to quickly find answers to auditor questions like;

- What are all the _actions_ take on _item A_ within the _time frame_?
- What _actions_ did _user A_ take within the instance _today_?
- _When_ was _item A_ last _published_?

With a few taxonomies standing out;

- actions (create, save, publish, etc.)
- resources (content, code, users, etc.)
- time

We could possible use these to create log statements with important details highlighted.

e.g.
**sample_page** was **Published** by **Stuart** on **Thursday**

---

@kakoga one concern I'd have with grouping by "sample_page", as you show an example of, is that the actions on that page aren't equal. For example; if I wanted to understand when sample_page was last published if I could to audit trail and sample_page actions are grouped what if the last one was a save but it's last publish is grouped with the save action at the top. How will I know that expand that group and see when the last publish occurred on it.

Would groupings be alternate views? As in a stream of chronological logs would be the default view but you could select filters to view the data by different grouping criteria.

**Comment by shrunyan** [comment]
Additionally we should consider any additional viewing experiences with the search bar in mind. While the search needs to get fixed to find all records from the API, versus the ones in memory, does it not already provide an elegant solution to the need? That is, can't someone already paste in a ZUID and get a filtered list of logs for that resource? 

Is it about providing accelerators to common use cases? As in, there would be a lot of mental overhead for a user to find another users ZUID and then search the logs for the actions take by that user so why not just roll that up into an experience.

**Comment by shrunyan** [comment]
Closed https://github.com/orgs/zesty-io/projects/42
