### ISSUE TITLE
Feature: Personalized Dashboard for 2021

### ISSUE THREAD

**Issue by ardeay** [zesty-io/manager-ui#472]
**Overview**

The current dashboard is an unused space that shows an Google Analytics placeholder that is unused. The goal of this improvement is to make the dashboard usable and helpful for the user.

This feature improves the dashboard by giving the user quick access to recent edits, publishes, including insight into their teams editing, access to areas they use frequently and linked resources. 

**Feature is documented here**

https://docs.google.com/document/d/1iPEE4zXexxdSbylBntrqXJURr4UfVWsZUM4X5oUifR0/edit#

**Wireframe**

![image](https://user-images.githubusercontent.com/729972/107271925-c9516b80-6a01-11eb-8c34-ea6d0571f435.png)

Original: https://user-images.githubusercontent.com/729972/106034634-00ca2a80-6088-11eb-8b63-39a164dd4622.png

**Comment by kakoga** [comment]
This dashboard has always been content-user driven. Could this dashboard be made more usable for all users by giving them the ability to see what would be most useful to them? In other words - a developer could see the latest code files edited and published. 

The Settings could have a section for the dashboard where a user could use checkboxes (IDE files, Schema, Content) to set what they want to see in certain places in the dashboard. Or perhaps the setting could only toggle between a dashboard for a content user or a developer user. The content user would see the dashboard as shown above and the developer user would see the edits and publishes for IDE files, not for Content. 

It might also be helpful for developers to be able to see what models have been created as well - could there be an optional box for that? eg Models Created - Models Edited. That might be helpful for large, distributed teams who frequently edit their instance. 

In those cases I imagine that the UI could use something like masonry.js to adjust the flow of the boxes in the dashboard.

**Comment by kakoga** [comment]
I would love to have the Zuid easily accessibly in the dashboard as well. Legacy dashboard showed that and I often used it.

**Comment by shrunyan** [comment]
> I would love to have the Zuid easily accessibly in the dashboard as well. Legacy dashboard showed that and I often used it.

That can now be found in the instance name dropdown located at the top left of the app shell

**Comment by ardeay** [comment]
A top left card showing the logo, instance name, and instance zuid, and link to domains registered.

**Comment by shrunyan** [comment]
@d88naimi I'll want you to tackle this request.

**Comment by shrunyan** [comment]
@d88naimi something I'll want you to read up on and bring a mind set of to this work is accelerators. https://www.nngroup.com/articles/ui-accelerators/

Beyond the cards which bubble useful insights into the instance activity the vast majority of the proposed interface is about providing personalized shortcuts.

**Comment by ardeay** [comment]
@kakoga wireframe updated to have accounts overview data 
![image](https://user-images.githubusercontent.com/729972/107271908-c0f93080-6a01-11eb-8eb9-20e6c52f1882.png)

**Comment by dhakimzadeh** [comment]
It would be ideal to have some way to add custom boxes here, 

- either select which to customize, or choose a box size and placement
- some of my admins only login once every few months
- i'd like to create custom boxes with quicklinks to their most common tasks, ie, add new rules, or create blog


- on a related note, being able to spin up quick help boxes would also be useful
- like bullet lists, basically a simple wysiwyg, to create quick links and help text
