### ISSUE TITLE
Media: Collapse folders on load of media section

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#489]
**Is your feature request related to a problem? Please describe.**
The media section used to load with the folders closed or collapsed - now it doesn't and it's difficult to sift through many folders to find the image that I need.

**Describe the solution you'd like**
It would be great for the Media section to load with the folders collapsed to make it easer to find what I need. 

**Describe alternatives you've considered**
1. the Media section could 'remember' a user's settings that would be helpful so a user could set their preferences... (Legacy appears to do something like this - in whatever form I leave the folders - expanded or collapsed - top level or child folders - when I re-open Media it's in that state)
2. add a toggle to the Settings where a user could say whether they want the Media folders collapsed or expanded on load. 

The current practice is to scroll and collapse folders to try to find the one I need. I would love the functionality of Legacy in Manager UI.

**Additional context**
<img width="1382" alt="Screen Shot 2021-02-05 at 2 15 54 PM" src="https://user-images.githubusercontent.com/16694502/107097491-e7c92400-67c1-11eb-8a00-ec2fe9f7cd64.png">

**Comment by kakoga** [comment]
A customer has requested this - I would like this as well.

**Comment by shrunyan** [comment]
In the new experience are they loading expanded even after you have re-collapsed and re-loaded? Or does it persist you collapse choices once remade?

**Comment by shrunyan** [comment]
Looping @nibblebot into this issue.

**Comment by kakoga** [comment]
oh dear - you're correct - it looks like it'll remember it in the new UI - I don't know why I didn't try that before it looks like it _does_ remember but I guess it was confusing because I had to reset those 'preferences' in manager UI when i just expected it to the the same no matter which one I opened (manager UI or legacy)

**Comment by kakoga** [comment]
I'll check with the customer to make sure that they have the same experience.

**Comment by shrunyan** [comment]
@kakoga can this issue be closed?

**Comment by kakoga** [comment]
Yes, I'll go ahead and close it 😅
