### ISSUE TITLE
Legacy web headers do not display in the UI and cannot be deleted via API

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#497]
**Describe the bug**
Instances with legacy web headers are seeing head tags rendering but have no way of editing/deleting them.

**To Reproduce**
1. Please see ticket for instance reference: https://zestysupport.zendesk.com/agent/tickets/1208
2. See that head tag in question is not visible in the instance Settings > Headtags section
3. The only way to pull this legacy headtag is using this endpoint: https://instances-api.zesty.org/#1b097314-1e85-450f-86f7-186f1a3f080f 
4. There is no endpoint to delete/edit the headtag

**Expected behavior**
Expect to be able to see and edit all head tags which are being loaded by Zesty in the Manager UI

**Additional context**
This has been brought up by a client, please reference the ZenDesk ticket linked above or message me directly :)

**Comment by d88naimi** [comment]
@giseleblair I don't have access to zendesk support can I get a little more context please? Is this still a valid issue?

1) Not familiar with what legacy web headers mean?
2) Can you attach a instance that I can verify with steps to reproduce? 



![Screen Shot 2022-01-03 at 4 09 47 PM](https://user-images.githubusercontent.com/22800749/147993506-fc42883c-b261-4f94-b613-0c3c37a25669.png)

**Comment by d88naimi** [comment]
Notes *

https://instances-api.zesty.org/#6da58f51-c6cc-4f5c-ba05-9acb82579316
/web/headers only offers a GET request and does not allow user to delete or edit legacy head tags. 
User at the moment can only request support to edit or delete the legacy head tags 

1) My recommendation is to add a Notice letting user's know that they need to contact support if they wish to delete legacy head tags.

CC @shrunyan

**Comment by theofficialnar** [comment]
Hi @zcolah, we'd like to request your input on how to show a notification message on the head tag settings to let users know if there are any legacy head tags on their instance and that they need to contact support to change these.

**Comment by theofficialnar** [comment]
Discussed with Zosh that we'll be using the same notification message that's being used to let users know about the head tags not being versioned.
