### ISSUE TITLE
Settings: Error on sub category

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#503]
**Describe the bug**
In Manager UI clicking into Settings > Styles > any category will return an error message

**To Reproduce**
1. Manager UI
2. Settings
3. Scroll down to Styles
4. Click any sub category
5. See error message

**Expected behavior**
Expect to see styles load per sub category selected.

**Screenshots**
https://www.loom.com/share/9ea4a32dd61b48aba85bed4bef42c73a

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Browser: safari + chrome

**Comment by kakoga** [comment]
It seems that this might only be certain instances - I tested on several of my kim test... instances and didn't get this error. 
When I looked back at one of the instances that erred there is a javascript error in the console: cannot read property 'split' on undefined

**Comment by giseleblair** [comment]
It looks like if there is a faulty font installed then the styles will not load. There needs to be more direction in the error message to help users resolve the issue in the UI.
