### ISSUE TITLE
Content: feedback on CSV upload errors

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#506]
**Is your feature request related to a problem? Please describe.**
When uploading a CSV and it fails, it's not always apparent what the issue is. It takes trial and error to figure out what went wrong.

**Describe the solution you'd like**
It would be helpful if the UI gave verbose feedback for upload errors such as: missing comma on line xx, duplicate item on line xx, required field missing content on line xx, etc. to help the user troubleshoot instead of uploading repeatedly using guesswork to debug failed uploads.

**Additional context**
see ticket: https://zestysupport.zendesk.com/agent/tickets/1185

**Comment by d88naimi** [comment]
Duplicate : https://github.com/zesty-io/manager-ui/issues/155
