### ISSUE TITLE
Customer Request: Form Builder

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/manager-ui#524]
**Is your feature request related to a problem? Please describe.**
Of the last 3 sales cycles, 3 prospects have asked about a form builder feature. This has also been suggested by current customers.

**Describe the solution you'd like**
A form builder should provide a non-technical user the ability to create fields, enable required fields, put in placeholder text (if needed), as well as defining if email notifications are sent when a form is submitted and if so to whom, a thank you pop up for the customer post submission, define where data flows after submission, etc. 

**Describe alternatives you've considered**
POWR has a great, intuitive form builder that may seem a little SMB but I think could provide a useful starting point re: UX. https://www.powr.io/plugins/form-builder

**Additional context**
N/A at this moment

**Comment by d88naimi** [comment]
@chloespilotro there is Wufoo forms that are pretty customizable https://www.wufoo.com/. Building our on form would be pretty awesome.

**Comment by d88naimi** [comment]
Most third party forms can be added simply with adding a head tag or JS script. Here is a list of the most popular forms to achieve custom forms in the mean time. This may add value in the future with Zesty's App store once built, in the mean time I am closing this ticket out.

https://www.g2.com/products/wufoo/competitors/alternatives
