### ISSUE TITLE
Customer Request: Page Builder/Component Builders

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/manager-ui#526]
**Is your feature request related to a problem? Please describe.**
Several prospects have asked about a drag-and-drop experience to page building. That could be cool, but a decent compromise might be a component builder. 

**Describe the solution you'd like**
A component builder should have the ability to create the layout and content of a set of items - for instance, a set of products. Once the component exists, it would be ideal to be able to "drop" that exact component (and its code snippet) on multiple pages without rebuilding it over and over again. Additionally, it should only be editable in one area, and changes should push to all of the pages the component lives on. 

It has also been suggested that components have the ability to be changed/edited based on the page. For example, if a customer has an article component (set of articles), they should be able to essentially choose to clone the component rather than use it, so that they can edit it for different landing pages the component is on, without changing it everywhere all at once.

**Describe alternatives you've considered**
N/A

**Additional context**
I'd recommend thorough market research and customer interviews to fully understand expectations before planning this build.

**Comment by d88naimi** [comment]
This is a WIP here : https://github.com/zesty-io/app-content-composer
