### ISSUE TITLE
Content items in sidebar not reordering

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#533]
**Describe the bug**
Items in Content app sidebar not reordering after saving in the Reorder Modal.

**To Reproduce**
1. Go to an instance's Content app.
2. Click on the Reorder button
3. Drag and drop to reorder items and hit Save.
4. See that saved changes are not reflected in the UI

**Expected behavior**
Expect the UI to display items in the order the user has saved using the reorder modal.

**Screenshots**
https://www.loom.com/share/ff5fde2019a14ec7acf02078087dff87

**Desktop (please complete the following information):**
 - OS: macOS Big Sure
 - Browser: safari + chrome

**Additional context**
This also has similar behavior to #518 where dragging/dropping does not immediately maintain that state. But additionally, the re-ordered items on "Save" are not reflected in the UI. 
<br><br><i>(related to <a href='https://zestysupport.zendesk.com/agent/tickets/1152'>Zendesk ticket #1152</a>)<br>gz#1152</i>

**Comment by kakoga** [comment]
A customer has reported this issue as they were reordering items the sidebar did not reflect their actions.
