### ISSUE TITLE
Workflow Request button hangs and doesn't appear to send request

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#539]
**Describe the bug**
When submitting a workflow request clicking the SEND button will gray out the button and add a loading gif with the word 'sending' - and it hangs in that state. (there is send-mail CORS error in the console too ).

**To Reproduce**
1. Go to a content item
2. Click on the Workflow Request button in the right-hand sidebar
3. Fill out the workflow request form and click the SEND button
4. See button hang as grayed out with loading gif

**Expected behavior**
When I click the send button I expect for the button to show in that state while the form is sending and then get a success/error notification depending on whether the POST was successful.

**Screenshots**

<img width="1361" alt="Screen Shot 2021-03-03 at 11 11 58 AM" src="https://user-images.githubusercontent.com/16694502/109859028-607c9e00-7c11-11eb-9e06-9600c05960b1.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 88
<br><br><i>(related to <a href='https://zestysupport.zendesk.com/agent/tickets/1290'>Zendesk ticket #1290</a>)<br>gz#1290</i>

**Comment by kakoga** [comment]
I wanted to bump this one up in the queue as this is a key feature and is used in demoing to prospective customers.

**Comment by kakoga** [comment]
Agent comment from Kim Koga in <a href='https://zestysupport.zendesk.com/agent/tickets/1290'>Zendesk ticket #1290</a>:  
  
+1 customer followed up on the status this today.

**Comment by shrunyan** [comment]
Fixed https://github.com/zesty-io/manager-ui/pull/634
