### ISSUE TITLE
Internal/External link - add publish and delete button

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#551]
placeholder - will fill out issue

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shrunyan** [comment]
I do not think we will take on a "publish" feature for Links in the near term. We would need to evaluate the intent, need and level of effort of such a feature. With the level of effort being known upfront as extensive.

A "delete" feature should be doable and easily matches to a need and low level of effort.

**Comment by kakoga** [comment]
Yes at the very least a delete feature would be excellent!

**Comment by d88naimi** [comment]
PR: https://github.com/zesty-io/instances-api/pull/349

![Screen Shot 2022-01-04 at 9 06 55 AM](https://user-images.githubusercontent.com/22800749/148096487-6301d706-f9cf-4436-9f80-ef9f56e8522e.png)
