### ISSUE TITLE
Swap Legacy Door Link with Github Octocat with manager-ui github link

### ISSUE THREAD

**Issue by ardeay** [zesty-io/manager-ui#556]
* Replace the legacy manager link in the bottom left corner with a github octocat icon that links to manager-ui Github Repo 
* text-align: center the hash so it stacks evenly

![image](https://user-images.githubusercontent.com/729972/110543667-74c40d80-80df-11eb-83a3-aa46ee3fb1ad.png)

**Comment by d88naimi** [comment]
legacy manager is deprecated closing this one out
