### ISSUE TITLE
I18n: deleting an item in 1 lang will also delete all siblings

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#562]
This straddles the line of enhancement and bug - I am filing this as a bug as it performs contrary to the user's expected behavior

**Describe the bug**
when the an item is deleted in 1 language, all of its siblings are also deleted. For example, if you have an item in EN-US, ES-MX, FR-FR and you delete ES-MX - all of the other languages (EN-US and FR-FR) will be deleted too.

**To Reproduce**
1. Go to an item that is in multiple languages
2. Delete an item in 1 of the languages
3. See that all other languages are deleted too.

**Expected behavior**
deleting 1 multilang item will NOT delete its siblings. ie all multilang entries can be delete individually. 

- it would be great if on click of the delete button they would have the option to delete _all_ siblings, or simply _this_ item.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Mac
- Browser Chrome
- Version 88

<br><br><i>(created from <a href='https://zestysupport.zendesk.com/agent/tickets/1315'>Zendesk ticket #1315</a>)<br>gz#1315</i>

**Comment by kakoga** [comment]
Agent comment from Kim Koga in <a href='https://zestysupport.zendesk.com/agent/tickets/1315'>Zendesk ticket #1315</a>:  
  
from a customer who reported this:
>fwiw I have been having to manually refresh indexdb a lot with the new manager ui, same with having my admins do it.  dropdown lists and loc stuff

**Comment by shrunyan** [comment]
This is by design. A multi-lang instance is a one-to-one page for every active language. i.e. A page should either be present or not present across all languages for the instance.

**Comment by kakoga** [comment]
Ok, then I'd like to propose an enhancement to this where deleting a sibling doesn't remove all of them. This would be very helpful in the case of having promotions in different countries that end at different times or having a promo only in 1 country, special sales by country, etc. Should I enter enter a feature request and link it back to this? or can this suffice as the feature request and I can change the label from bug to enhancement?

**Comment by shrunyan** [comment]
I'm not sure it's something we would take on. If content is differing at extensively between languages then a multi-instance setup should be used. 

The design is that a content item with multiple alternate languages is treated as a cohesive set. If that content item is deleted, whether the original or an alternate language, then the indication is that set of languages is to be deleted. i.e. One can't exist without the other.

Having content be live at different times within the alternate languages is currently possible by schedule publishing whichever version of a language is desired.

**Comment by kakoga** [comment]
Ok, yeah - that makes sense - I guess if I customer would like to do something like having an item published/unpublished in different languages - using publish and list settings is the way to achieve this. 
I'll let the customer know that this is the expected behavior for deleting a multi-lang item.

**Comment by kakoga** [comment]
followed up with customer on this workflow - using unpublish or list settings to hide items in specific languages and also let them know that the delete behavior they experienced is what's expected -  therefore closing this ticket.
