### ISSUE TITLE
Global tabs ordering 

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#577]
**Is your feature request related to a problem? Please describe.**
When working in multiple files it can be difficult to find the tab that you're working on because the current tab always appears at the left - therefore whenever you click into a new file the order of tabs gets jumbled up and it's difficult to follow.

**Describe the solution you'd like**
the customer would like the tabs to stay in the order that they're opened in - this would keep a user from searching for tabs. 

Customer also thinks that it would be helpful to have tabs that have no changes to them to automatically close. 

**Additional context**
This is a customer request - please see the linked ticket below.<br><br><i>(created from <a href='https://zestysupport.zendesk.com/agent/tickets/1257'>Zendesk ticket #1257</a>)<br>gz#1257</i>

**Comment by shrunyan** [comment]
This will be resolved with issue https://github.com/zesty-io/manager-ui/issues/629
