### ISSUE TITLE
wysiwyg content does not update as you toggle through previous versions in Manager UI

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#614]
**Describe the bug**
In the Manager, when you are editing a content item, toggling through previous versions of that item does not update the previous content of the wysiwyg field type.

https://www.loom.com/share/81c302ac27e548ad8e5f83d299700ea2<br><br><i>(related to <a href='https://zestysupport.zendesk.com/agent/tickets/1329'>Zendesk ticket #1329</a>)<br>gz#1329</i>

**Comment by shrunyan** [comment]
Duplicate https://github.com/zesty-io/design-system/issues/97
