### ISSUE TITLE
Web IDE: allows user to delete loader without warning

### ISSUE THREAD

**Issue by simonprickett** [zesty-io/manager-ui#62]
The editor in the manager allows the user to delete `loader` without warning.  This then breaks every HTML page on the site and it is not obvious what has happened or that the user needs to add a `loader` back with a call to `{{current_view}}` before anything will work again.  This is a terrible product experience.

Suggest some combination of the following to improve this:

* Don't let the user delete `loader` at all, and parse it for `{{current_view}}` to validate when saving
* Let the user delete `loader` and have the system fall back to one that contains just `{{current-view}}` if it doesn't find a file called `loader`
* Let the user delete `loader` but only after they have OK'ed an explicit message that tells them that this will break all HTML pages on their site (which may be OK for example if the instance they are working with has no HTML views because it is a pure backend)

**Comment by shrunyan** [comment]
@d88naimi lets implement the following on the UI.

- Lock icon only for the `loader` file.
- Hide the "delete" button when viewing the file in the code editor.
