### ISSUE TITLE
SEO: typeError being thrown

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#627]
**Describe the bug**
Navigate to manager-ui SEO page select the "Type"  and open console log there is error 

**To Reproduce**
1. Go to https://8-f48cf3a682-7fthvk.manager.zesty.io/seo
2. Click on 'type'
open console

**Expected behavior**
sort type correctly

**Screenshots**
<img width="798" alt="Screen Shot 2021-03-30 at 1 35 24 PM" src="https://user-images.githubusercontent.com/22800749/113053391-137edf80-915d-11eb-8183-889601c0ecd5.png">

**Desktop (please complete the following information):**
 - OS: [mac]
 - Browser [ chrome]

**Comment by shrunyan** [comment]
This appears to fixed
