### ISSUE TITLE
Tab Experience: When Tab is Clicked, Keep it in it's position

### ISSUE THREAD

**Issue by ardeay** [zesty-io/manager-ui#630]
Right now when you click a tab that is already opened, it appends that tab to the front of the list, this often falls out of the users view. See the attached video for an explanation.

https://www.loom.com/share/6c128b4281b04f2dbfe76b4e2bcf8ca4

**Comment by shrunyan** [comment]
This will be resolved with issue https://github.com/zesty-io/manager-ui/issues/629
