### ISSUE TITLE
Tab Experience: fixed width tabs

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#633]
**Is your feature request related to a problem? Please describe.**
it's cumbersome to close many tabs as the close button positioning relies on filename length.

**Describe the solution you'd like**
Move the X close icon to the left side of the tab therefore it is always in the same position and I can click in 1 place to close all my tabs. 

<img width="1403" alt="Screen Shot 2021-03-31 at 1 41 18 PM" src="https://user-images.githubusercontent.com/16694502/113211087-db919e00-9229-11eb-9b58-640c4eebef03.png">

**Comment by shrunyan** [comment]
@kakoga I would propose we keep the close action in the same location. As that is the common location between browsers and IDE, the experience we are base this off of. 

We could mimic Chromes browser tab behavior be determining a static width based upon the amount of tabs and the available view space. Where we would probably break with Chrome in this behavior is having a minimum width for tabs, at which point we would render an overflow.

Alternatively we could add a button which would close all open tabs. The tricky part with this is a design which works with the existing layout.

**Comment by kakoga** [comment]
Yes a fixed width would be really helpful in terms of quickly closing tabs. I feel like we don't need to have `close all` button if we have fixed width tabs. I agree that a button might be tricky to include in the UI.
