### ISSUE TITLE
Instant API link missing for content items

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#639]
**Describe the bug**
The Instant API link can be seen in the Schema section for the Content Model but it is not shown in the Content section for single content items.

**To Reproduce**
1. Go to Content
2. Click on an item to see it's content fields
3. See right hand sidebar missing Instant API link

Schema:
<img width="1643" alt="Screen Shot 2021-04-07 at 11 47 27 AM" src="https://user-images.githubusercontent.com/9896546/113895884-6842db80-9797-11eb-8df0-d0a023373204.png">

Content:
<img width="1638" alt="Screen Shot 2021-04-07 at 11 46 44 AM" src="https://user-images.githubusercontent.com/9896546/113895908-6ed15300-9797-11eb-899c-e98aea689311.png">

**Comment by shrunyan** [comment]
My guess is that the permission check that determines whether this appears has not been updated with the new `usePermission` hook.
