### ISSUE TITLE
SEO app: no matches message displays after selecting path

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#640]
**Describe the bug**
When using the search field to search for an existing path, the results will display but when the user clicks on the item an error message displays. 

**To Reproduce**
https://www.loom.com/share/df97f5813f0549749164aa79277ea8c6

**Expected behavior**
There should not be an error message when the user clicks on the listed item.
<br><br><i>(related to <a href='https://zestysupport.zendesk.com/agent/tickets/1831'>Zendesk ticket #1831</a>)<br>gz#1831</i>

**Comment by shrunyan** [comment]
After selection from the options list the list should close.
