### ISSUE TITLE
SEO: Wildcard redirects

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#643]
**Is your feature request related to a problem? Please describe.**
WebEngine now supports wildcard redirects, as well as 3 types of redirects `path`, `external`, and `page` that are not available to customers through the current redirects UI

**Describe the solution you'd like**
We should update the app to give the user three options to make a redirect and include links to documentation.
**Describe alternatives you've considered**

API Documentation on this feature is located: https://instances-api.zesty.org/#1fdabbe3-e977-4ea5-8a4b-81ce29598263

Individual APi docs for the different types of redirects
* `path`: https://instances-api.zesty.org/#38bf3fb8-44b1-4b22-a743-376c42fda624
* `path` with Wildcard: https://instances-api.zesty.org/#4e35194e-ce30-43a0-bfe2-91bc76e5a627
* `page` (ZUID): https://instances-api.zesty.org/#9dbf6a75-cb3e-4292-850b-1e78979bd035
* `external`: https://instances-api.zesty.org/#0e1a4940-3d7f-4e59-bd3d-9b06be44d9a3

Zesty.org docs https://zesty.org/services/web-engine/30x-redirects

## Desired Update

The current UI only creates a `path`, the UI should be updated to create the 3 types of redirects.

The current UI lends itself to to work with a couple changes:

**Change 1:** The dropdown search for pages should stay, but on select it should populate with a ZUID
**Change 2:**  The "to" input should not strictly enforce the value to a path, but also a ZUID or full URL with protocol
**Change 3:** Type assumption should be made based in on the incoming string. This would change the post request type value. An assumption on the incoming target string can be made like this:
* any string that include HTTP is of type `external`
* any string with a ZUID (7-xyz-xyz) is of type `page`
* If the above does not match, default to type `path`

Change 4: Titles should change from "From" to "Incoming Path" and "To" to "Redirect Target"

**Comment by ardeay** [comment]
@shrunyan updates made to your initial issue post

**Comment by ardeay** [comment]
See the desired update in the original post. @d88naimi 

The UI needs to know to change the target type in the payload based on the string 
![image](https://user-images.githubusercontent.com/729972/127187515-990c8083-86b7-44aa-8dd9-c39de2bbedfa.png)
![image](https://user-images.githubusercontent.com/729972/127187477-3f6d42e7-5bb5-417a-9db1-709c068f0dff.png)

**Comment by ardeay** [comment]
The request is not pulling from the value from the input 
![image](https://user-images.githubusercontent.com/729972/127187826-a8c4f369-6686-45e3-89eb-44807fb3c6cd.png)
