### ISSUE TITLE
Content editing item deep link to AuditTrail

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#658]
**Is your feature request related to a problem? Please describe.**
In the edit item view there is a PublishTrail and EditTrail widgets. This widgets show the 5 latest actions of those types on the item being viewed. There should be a link to see additional actions on the item.

**Describe the solution you'd like**
The card footer widget should contain an app link which deep links to AuditTrail filtered to the item zuid being viewed. Allowing a user to see additional actions, beyond the limit of 5, taken on that item.

**Describe alternatives you've considered**

**Additional context**

**Comment by rjpals** [comment]
Closing as completed via #1242
