### ISSUE TITLE
SEO Redirect From field doesn't validate paths

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#695]
**Describe the bug**
We can only make redirects in the UI for relative paths. However I'm able to add redirects with invalid strings. 

**To Reproduce**
1. Go to SEO section
2. In the From field add some text like: http:/example - and then add an item in the TO field
3. Click 'create redirect'
4. See that redirect is created

**Expected behavior**
I would expect that any text that is added to the From field is validated before a redirect is able to be created. 

**Screenshots**
<img width="1306" alt="Screen Shot 2021-05-11 at 2 00 21 PM" src="https://user-images.githubusercontent.com/16694502/117884556-9ff2e680-b261-11eb-888c-2f19657965d2.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 89?? 

**Additional context**

**Comment by shrunyan** [comment]
Is this request expressing the UI should guard against malformed urls or the "from" input should enforce root relative paths?

**Comment by shrunyan** [comment]
Related to https://github.com/zesty-io/manager-ui/issues/696

These should be resolved with a cohesive solution.

**Comment by kakoga** [comment]
@shrunyan What i'm trying to convey is that I think that the input should only allow inputs that begin with a / as we can only redirect relative paths. therefore, if a person inputs https... etc. it should throw an error. And I think that the error should communicate what the issue is.

 I realize that if a user inputs a correctly formed URL it will throw an error. However I think it should also protect against other types of inputs such as www.example.com. 
 
 I want to advocate for better communication in this section. I think we need to tell customers that we can only redirect relative paths and show an example too because as it is it's not clear. 
 
 Does that help clarify what I am asking for?

**Comment by agalin920** [comment]
API currently does not restrict these paths in the way requested. This should probably be solved on the BE side as opposed to adding client-side validation
