### ISSUE TITLE
Schema: field reference names do not autopopulate

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#703]
**Describe the bug**
field reference names no longer auto populate and I have to type them in manually. 

**To Reproduce**
1. Go to Schema
2. Click on any existing model and add a field.
3. When you type in the Field Label notice that the Field Name does not autopopulate.

**Expected behavior**
I expect the Field Name to populate with whatever I type into the Field Label field. 

**Screenshots**
<img width="718" alt="Screen Shot 2021-05-17 at 11 48 15 AM" src="https://user-images.githubusercontent.com/16694502/118541118-344bc600-b706-11eb-8aff-953c3b615377.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 90

**Additional context**
I _think_ that this only started to happen recently. I don't know if this change was intended. I think that making user enter the reference name leave space for mistakes that we should eliminate.

**Comment by ardeay** [comment]
@d88naimi bump

**Comment by d88naimi** [comment]
@nibblebot I have tried multiple attempts at this one. I fixed the original issue here https://github.com/zesty-io/manager-ui/pull/692, but introduced the reported bug above. Lifting this up to the big guns @nibblebot

**Comment by d88naimi** [comment]
@ardeay I synced up with @nibblebot  about this one. We are currently blocked as making the form controlled with `value` fixes the auto-populate but breaks the input field with a cursor jump. Leaving as uncontrolled `defaultValue` for now fixes the cursor jump but breaks the auto-populate. Leaving as is until further directions. 

1) One solution is to implement https://react-hook-form.com/ 

2) Another solution is to make the form controlled but remove the isDirty functionality. 

This issue should be converted to a project.

**Comment by ardeay** [comment]
Do what it takes to get that field populating for now, even if that means its locked to the title input.  CC @d88naimi @shrunyan
