### ISSUE TITLE
Parsley reference 

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#760]
**Is your feature request related to a problem? Please describe.**
Content title should show Parsley code reference next to title for easy reference 

**Describe the solution you'd like**
next title in a secondary color `zesty-light-gray` add the Parsley reference

![parsley-reference](https://user-images.githubusercontent.com/22800749/122613489-c9114e80-d039-11eb-99b7-3c4ddb57400a.png)

**Comment by d88naimi** [comment]
@ardeay  Can you confirm if I have added Field Label names to the correct places? There are 18 use cases of labels but not 100% if all are need. In screenshot ive added field label names to 9 location (screen shot red ) 

![FieldLabel](https://user-images.githubusercontent.com/22800749/122830987-0d048d80-d29e-11eb-9ea5-4d1061a2ce49.png)

**Comment by ardeay** [comment]
@d88naimi we had a phone call to discuss, when ready, please paste your screenshot updates into this thread

**Comment by d88naimi** [comment]
@ardeay Round 1 complete let me know what you think. 
Adding font-weight bold 600 - 800 were all the same boldness.

<img width="595" alt="Screen Shot 2021-06-21 at 4 40 57 PM" src="https://user-images.githubusercontent.com/22800749/122840812-b2742d00-d2af-11eb-909c-a958164e0ed0.png">
<img width="582" alt="Screen Shot 2021-06-21 at 4 41 06 PM" src="https://user-images.githubusercontent.com/22800749/122840814-b3a55a00-d2af-11eb-93d9-e563e550a20c.png">
<img width="704" alt="Screen Shot 2021-06-21 at 4 41 38 PM" src="https://user-images.githubusercontent.com/22800749/122840816-b3a55a00-d2af-11eb-8ba4-e611157e5a9e.png">
<img width="236" alt="Screen Shot 2021-06-21 at 4 41 52 PM" src="https://user-images.githubusercontent.com/22800749/122840818-b3a55a00-d2af-11eb-96b5-d7ef3a8ac104.png">
<img width="738" alt="Screen Shot 2021-06-21 at 4 42 02 PM" src="https://user-images.githubusercontent.com/22800749/122840819-b43df080-d2af-11eb-8cb4-98ab9ae47d69.png">
<img width="473" alt="Screen Shot 2021-06-21 at 4 42 08 PM" src="https://user-images.githubusercontent.com/22800749/122840821-b43df080-d2af-11eb-93dc-b334f1d7c0dd.png">
<img width="1608" alt="Screen Shot 2021-06-17 at 10 38 38 AM" src="https://user-images.githubusercontent.com/22800749/122840822-b43df080-d2af-11eb-9120-366a3470c914.png">

**Comment by shrunyan** [comment]
Have we previewed this on any customer instances in stage? The testing instance repeating things multiple times looks bad.

**Comment by d88naimi** [comment]
@shrunyan 
@ardeay and I peer programmed this together. Please let me know how to proceed or leave as is.
