### ISSUE TITLE
Dashboard button / content filter 

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#762]
**Is your feature request related to a problem? Please describe.**
Dashboard button 

**Describe the solution you'd like**
Make a global Dashboard button for easy access, open to recommendations on location placement.
CC: @ardeay

**Comment by ardeay** [comment]
Put it in the nav near the CONTENT label

**Comment by ardeay** [comment]
![image](https://user-images.githubusercontent.com/729972/123006362-620ed500-d36c-11eb-9cee-d4b7297d3cc4.png)

**Comment by d88naimi** [comment]
@ardeay due to the limited space of the Nav I placed the dropdown under the new filter search and the Dashboard link next to Content title. Let me know what you think so far thanks.

<img width="369" alt="Screen Shot 2021-06-23 at 10 30 48 AM" src="https://user-images.githubusercontent.com/22800749/123142272-17de3000-d40e-11eb-840e-43d73f625bfa.png">
