### ISSUE TITLE
Close All Tabs button 

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#763]
**Is your feature request related to a problem? Please describe.**
Close All Tabs button to help overall workflow

**Describe the solution you'd like**
Close All tabs button open to suggestion on location. Possibly remove Global Search Icon and place close all button there 

![close-all-tabs](https://user-images.githubusercontent.com/22800749/122614783-28705e00-d03c-11eb-8f49-0c2e48658695.png)

**Comment by shrunyan** [comment]
@d88naimi that real estate is pretty constrained. Lets us a [vertical ellipse icon](https://fontawesome.com/v5.15/icons/ellipsis-v?style=solid) that on hover reveals a fly out with options(for the mean time a single one). One being to close all tabs.

**Comment by rjpals** [comment]
No longer relevant after Tabs redesign
