### ISSUE TITLE
Add Docs link bottom left

### ISSUE THREAD

**Issue by ardeay** [zesty-io/manager-ui#783]
Book Icon with Docs (links to Zesty.org)

![image](https://user-images.githubusercontent.com/729972/123495499-c9c95800-d5d8-11eb-91b9-89dc28f1a0e0.png)

**Comment by d88naimi** [comment]
@ardeay We have quick access to to zesty.org in the menu, this would be come a duplicated link in the subNav. I could remove the help menu and add 1-3 of the most important links in the subNav without the nav becoming too busy?

**Comment by d88naimi** [comment]
After a discussion with @ardeay we decided to swap the help icon and title to Docs and Book icon while keeping all functionality the same.

<img width="210" alt="Screen Shot 2021-07-02 at 4 18 29 PM" src="https://user-images.githubusercontent.com/22800749/124336028-4e742300-db51-11eb-8b99-db04220a58bd.png">
