### ISSUE TITLE
A blank Content item is creating an empty row in ItemList table view

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#812]
**Describe the bug**
When creating a new item for a Multi Page Model and redirecting or leaving the unsaved item to another view, a empty row will be generated.

Also if you select the empty item and add text and create the item a new item will be created while the empty row is appended down the table. 

**To Reproduce**
http://8-f48cf3a682-7fthvk.manager.dev.zesty.io:8080/content/6-a2edaefaf7-hs9bdz
Advanced Publishing Example > create an item > leave empty > click back to Advanced Publishing Example > you will see an empty row being displayed, which leads to a confusing experience.

**Screen Share**
https://www.screencast.com/t/prtg390s

**Expected behavior**
When hitting back or redirecting to a different view, no visual changes should populate.

**Alternative solution **
Render the unsaved changes modal 
<img width="747" alt="Screen Shot 2021-07-12 at 10 12 38 AM" src="https://user-images.githubusercontent.com/22800749/125328896-b23cdf80-e2f9-11eb-82a5-1c02639277f4.png">

**Screenshots**
<img width="1326" alt="Screen Shot 2021-07-12 at 10 03 49 AM" src="https://user-images.githubusercontent.com/22800749/125328343-10b58e00-e2f9-11eb-9345-a6e7e180bfa3.png">

**Comment by ardeay** [comment]
@d88naimi look into sentry injecting data

**Comment by ardeay** [comment]
@shrunyan I saw weird data being injected to the nav trees, I also think this may be the cause of the sort issue that's was patched yesterday. Does sentry do that?
