### ISSUE TITLE
Ability to collapse toolbar in content view

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/manager-ui#839]
For those working on smaller screens, it would be great if you could collapse the nav view and the right hand settings pane in the content editor so that all the real estate is available for content editing. Please refer to screenshot as example 

https://zestyio.media.zestyio.com/Screen-Shot-2021-07-22-at-12.29.14-PM.png

**Comment by d88naimi** [comment]
@chloespilotro what size laptop are you on? 
What is your typical window size also? https://viewportsizer.com/what-is-my-screen-size/

**Comment by chloespilotro** [comment]
1433 × 796

13" 2020 macbook air M1 chip

**Comment by d88naimi** [comment]
Will be resolved with this PR: https://github.com/zesty-io/manager-ui/pull/932
