### ISSUE TITLE
New Items do not trigger Redux to Refresh the Content Tree

### ISSUE THREAD

**Issue by ardeay** [zesty-io/manager-ui#851]
New Items do not trigger Redux to Refresh the Content Tree

Created a new top level items

![image](https://user-images.githubusercontent.com/729972/127604146-d654da0d-2560-4710-8d82-ececfeb64a60.png)

After creating an item, it doesnt appear in the content tree

![image](https://user-images.githubusercontent.com/729972/127604182-8ca4e6c5-55c0-4057-8b42-90e8a9da041b.png)

Reported by @saraharmst of Ping Works - Sarsh reports: just clarifying the issue here, it's only in the manager ui that we've noticed the issue. No refresh on the content tree in the LHS is called after adding new items, so they only appear after interacting with the nav or refreshing the page

**Comment by shrunyan** [comment]
https://github.com/zesty-io/manager-ui/pull/852
