### ISSUE TITLE
Where ZUID appears in the UI, allow for auto population of the clipboard on click, or at least a auto select of the entire ZUID

### ISSUE THREAD

**Issue by Ben-Lai** [zesty-io/manager-ui#866]
Wherever the ZUID is listed in the UI
![image](https://user-images.githubusercontent.com/29470165/129301202-42ce558b-255e-43dd-b9ca-e1b43c89e430.png)
or
![image](https://user-images.githubusercontent.com/29470165/129301236-06beba24-97e6-43ae-9ec4-7619118dc845.png)
when you click on the ZUID, either copy directly to the clipboard automatically, or auto select the entire ZUID, or allow triple click to select the entire ZUID so the user can immediately copy. 

Triple Clicking at the moment selects the entire line including the field label, so it still requires editing after the copy.
![image](https://user-images.githubusercontent.com/29470165/129301355-88e27b55-51bd-44cd-b164-c5b4be67ed0e.png)

**Comment by shrunyan** [comment]
@d88naimi I think we could incorporate this into the design system with the concept of a "chip". There is prior art from the Material Design system. https://material.io/components/chips
> Chips are compact elements that represent an input, attribute, or action.

I imagine we would add an "atom" **Chip** component that contains the basic structure and styling. Then there would a "molecule" **CopyChip** component which incorporates the copy functionality with the base Chip component. This way we could add additional functionality chips at a later point using the same process.

**Comment by shrunyan** [comment]
Other locations of ZUIDs;

- global accounts menu flyout
- Code app drawer
- schema edit view
- AuditTrail logs
