### ISSUE TITLE
Concatenate lang code to end of multi language relational item

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#868]
When a user has multi-lang on an instance and they have relational fields throughout their content, it is difficult to note which item in a relational field belongs to what language. Because relational items have their default content set to the default lang, the user sees both the selected default item and the corresponding language items in a relational field. If the content of those items are the same, then the user won't know which item corresponds to the current language they are editing. To help resolve for this confusion, it will be helpful to concatenate the language code at the end of the item content in a relational field. 

<img width="1654" alt="Screen Shot 2021-08-16 at 9 28 08 AM" src="https://user-images.githubusercontent.com/9896546/129597802-aa89bcb4-387b-4375-8375-075cc96940a0.png">

**Comment by d88naimi** [comment]
@giseleblair Can you add me to a test instance with mulit lang? Also if possible a small clip on how to navigate between multi-lang please.

**Comment by giseleblair** [comment]
@d88naimi I added you to an instance and here is a recording of navigating through the langs:
https://www.loom.com/share/e7c4ebc4ac8540a2901cbcc17879c6ad
