### ISSUE TITLE
Content soft lock unnecessary when current user is only editing on one tab

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#875]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shrunyan** [comment]
@giseleblair I do not understand what the ask is in regards to the content lock.

**Comment by shrunyan** [comment]
We need to add a `window.beforeunload` which makes a request to the cache to unlock the current item.
