### ISSUE TITLE
Un-hiding content in content pane does not restore it to main view

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/manager-ui#879]
**Describe the bug**
Un-hiding content in content pane does not restore it to main view

**To Reproduce**
1. Go to content manager 
2. Hide a content item from view, it will move to **hidden** subnav below
3. open hidden items 
4. try to un-hide content item, it does not go return to main nav view

**Comment by shrunyan** [comment]
I am not able to replicate this behavior. 

- What browser are you using?
- What OS?
- Is the item you are hiding parented?
- What type is the item being hidden? Headless, Multi-page, Single page?

**Comment by d88naimi** [comment]
@chloespilotro I am unable to replicate this bug. Can you confirm it's still active or can I close this one out? Thank you.

**Comment by chloespilotro** [comment]
Sorry, missed this notification! I can no longer replicate either, I guess it's resolved. Thanks guys!
