### ISSUE TITLE
Sort Order field does not update content when toggling through previous versions

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/manager-ui#898]
**Describe the bug**
When selecting previous versions of a content item the sort field does not update to the previous sort order for the older version. Similar to the this issue, but for the sort field:
https://github.com/zesty-io/manager-ui/issues/614

**Expected behavior**
The Sort field updates to the older version content like the other fields. 

**Screenshots**
Manager ui view of version 7
![image](https://user-images.githubusercontent.com/50595614/134076320-a328243a-6440-4b66-9825-722d8aa0ab91.png)

API data for same item and version 7
![image](https://user-images.githubusercontent.com/50595614/134076724-b9363a64-b2d1-4edf-a166-72fc5e87c0c8.png)

**Comment by shrunyan** [comment]
This is an issue with the `[FieldTypeSort](https://github.com/zesty-io/design-system/tree/master/core/src/FieldTypeSort)` component from the design-system. Currently it is a controlled component and doesn't handle prop changes within it's internal state for the sort value.
