### ISSUE TITLE
accounts interface needs domain format validation 

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#924]
Currently, there is no validation when a user configures a domain to an instance. 

In Accounts UI, go to an instance and open its settings. Add a domain in the domain field without an extension such as `mydomain` without `.com` and the form accepts the input. This leads to confusion from users who think they have correctly configured a domain but do not see their content rendered as expected. 
![Screen Shot 2021-11-30 at 4 14 42 PM](https://user-images.githubusercontent.com/9896546/144074326-3853fef7-8105-414b-a41f-b182fbf36046.png)

**Comment by d88naimi** [comment]
PR here in Accounts-ui https://github.com/zesty-io/accounts-ui/pull/223

**Comment by d88naimi** [comment]
PR: https://github.com/zesty-io/accounts-ui/pull/223
