### ISSUE TITLE
CSV Import Bug

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/manager-ui#926]
**Describe the bug**
Once you get to a point in the drop down where you have to scroll down to select more fields in a CSV import, not only does the dropdown disappear, but all the other selected columns are deleted. 

**To Reproduce**
Please refer to loom https://www.loom.com/share/8f79fce2fee84ea780ca133ff8d15f72

**Expected behavior**
Expect to be able to select any item from a dropdown and for selected fields to not be deleted.

**Screenshots**
Please refer to loom 

**Desktop (please complete the following information):**
 - OS: iOS Big Sur 11.2.3
 - Browser: Chrome
 - Version: 96.0.4664.55

**Additional context**
N/A

**Comment by d88naimi** [comment]
Duplicate closing this one  https://github.com/zesty-io/manager-ui/issues/605
