### ISSUE TITLE
Media nav sorting

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#927]
**Is your feature request related to a problem? Please describe.**
When an instance contains many media groups it becomes extremely difficult to find a group. 

**Describe the solution you'd like**
Adding a button(s) which sort the nav by both alphabetical and creation date(current default) it will be easier to discover groups you know the name of.

**Describe alternatives you've considered**

**Additional context**
Customer feedback

![alphabetical-sort](https://user-images.githubusercontent.com/22800749/147965117-8693c765-48a6-47e6-a496-3d4da540e535.png)

**Comment by rjpals** [comment]
No longer relevant after Media redesign
