### ISSUE TITLE
Code editor maintain line number position

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#928]
**Is your feature request related to a problem? Please describe.**
While working on a code file a user will often be on a specific line number. When they need to reference a field they'll often switch to the schema app to find the field reference. When returning to the code file they were working on the cursor is placed at line number 1. Losing their prior place in the file.

**Describe the solution you'd like**
We should track the line number the cursor is on in a file. When a user returns to a code file view we should restore their cursor to the tracked line number.

e.g.

- Code file A open on line 570
- Capture line 570 into state
- User leaves code file A
- User returns to code file A
- Load code file A at line number 570
- 

**Describe alternatives you've considered**

**Additional context**

**Comment by d88naimi** [comment]
Duplicate : https://github.com/zesty-io/manager-ui/issues/413
