### ISSUE TITLE
Console  Warning: componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#943]
**Describe the bug**
Console Warning on RedirecTable.JS

line 22 : componentWillReceiveProps 
**Screenshots**
![Screen Shot 2022-01-18 at 11 49 43 AM](https://user-images.githubusercontent.com/22800749/150008578-a0958a5f-8f33-4b12-822e-8e37c43ac75d.png)

**Comment by shrunyan** [comment]
Will this be resolved with https://github.com/zesty-io/manager-ui/pull/964

**Comment by d88naimi** [comment]
@stuart Yes updated PR thanks
