### ISSUE TITLE
Improve media url editing

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#949]
**Is your feature request related to a problem? Please describe.**
Currently it is unclear that the '`filename` property of a media asset controls the url.

**Describe the solution you'd like**
We should combine the url and filename editing experience into a single field so it clearly communicates changing the filename changes the url. This will need to maintain a button to copy the url.

**Describe alternatives you've considered**

**Additional context**

**Comment by d88naimi** [comment]
@shrunyan  How about `Edit Filename URL` ?

![Screen Shot 2022-01-20 at 10 39 40 AM](https://user-images.githubusercontent.com/22800749/150401399-684ca47c-bb5f-4849-9bb6-9240066de205.png)

**Comment by agalin920** [comment]
@shrunyan PR ready for review
