### ISSUE TITLE
Dropdown cut off

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#957]
**Describe the bug**
When creating an item which has a field type of `internal_link` as one of the last fields which contains multiple records on the related model the dropdown gets cut off. Presumably because of an `overflow:hidden`

**To Reproduce**
1. Go to create new item with an internal link field at the end of the list which is related to a model with multiple entries
2. Click on dropdown

**Expected behavior**
Show complete list of dropdown options

**Screenshots**
![image](https://user-images.githubusercontent.com/208819/151068818-b5834ddc-959d-424d-9e78-edc56652e398.png)

**Comment by d88naimi** [comment]
@shrunyan this PR will fix this issue https://github.com/zesty-io/manager-ui/pull/956
