### ISSUE TITLE
New fields do not autopopulate code reference as field name is filled out

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#969]
When a user creates a new field, the code reference should auto populate as they fill out the field's label. Currently, it allows the user to create a field with a blank looking code reference which will then autogenerate that code reference using its field label. You can see that flow here:
https://www.loom.com/share/f831758d759444428ca3b4b8ad70aa4b

The solution would be that when a user creates a new field and starts typing out the field's label, that the code reference field is auto populated using the field label's value.

**Comment by d88naimi** [comment]
@giseleblair I think this is a duplicate from here https://github.com/zesty-io/manager-ui/issues/703
Here is a PR fix https://github.com/zesty-io/manager-ui/pull/861

**Comment by giseleblair** [comment]
Thank you, I was looking for the original. Please merge these two to capture the new video as well. Is the PR blocked at the moment or will it be going out soon?

**Comment by d88naimi** [comment]
@giseleblair blocked, @shrunyan may shed some more light on this one.
